### ISSUE TITLE
Shortcut Buttons for Transformations are able to be used when they shouldn't be

### ISSUE THREAD

**Issue by cheatfreak47** [leoetlino/project-restoration#1]
One major example is that you can use them while you are on Epona and that causes a softlocking issue that isn't much fun to deal with, since it seems easy to do this by mistake.

**Comment by leoetlino** [comment]
Yeah... I need to figure out what the official checking logic is and use that. Another example is using the shortcuts in Sakon's Hideout while you are controlling Kafei, which causes him to put on the Keaton Mask (lol) and crashes the game.

**Comment by leoetlino** [comment]
For Kafei, a quick fix would be to check for the player's active mask ID (which is 5 - Keaton Mask when controlling Kafei), but ideally we'd be using the same logic as Nintendo to determine whether items are usable.
