### ISSUE TITLE
Remove the hat transition while deku link is spinning

### ISSUE THREAD

**Issue by SamuelTheSuperb** [leoetlino/project-restoration#100]
I know this seems pretty insignificant, and it is, but unlike the original game, deku links hat transitions into a tree with spikes at the end. I think it looks really ugly, and I would love it if the hat stayed normal during the deku spin.
![image](https://user-images.githubusercontent.com/38936162/70833831-f4b4d800-1db5-11ea-8793-7a67d6add065.png)

**Comment by leoetlino** [comment]
This honestly doesn't bother me at all (the change kind of actually makes sense), so I will not be personally working on it. I doubt anyone would be unhappy if this were reverted though, so I'll still accept contributions for this feature request.
