### ISSUE TITLE
[Feature request] Please continue to provide IPS formats for at least v100 or a v9.1 Luma PLG Plugin Loader with BPS support

### ISSUE THREAD

**Issue by ImmortalZypther** [leoetlino/project-restoration#103]
**Please ensure the feature or the change you're suggesting isn't out of the scope of this project. In most cases, only bug fixes, beneficial MM3D change reversals or QoL improvements will be accepted.**

**Description**
As stated in the title, I'm requesting that you continue to provide the IPS format patch for at least revision v100 of Majora's Mask 3D.

**Additional context**
I'm requesting this because using the BPS patcher for Luma would be the **third** variant of Luma that I have to boot with fastboot3DS. The first one is the standard plugin loader for PLG files, the second is the plugin loader for 3GX files, the final would be this one, the patcher for BPS files. I know I'm probably one of few that has to deal with this issue, but I'm very sure that there's less of a minority using the BPS patcher as their second plugin loader if they want to use the plugin loader for PLG files. 
Here is the link to the PLG plugin loader, the major one that people use if they're using plugin loaders at all: https://gbatemp.net/threads/ctrpluginframework-blank-plugin-now-with-action-replay.487729/
Please, provide IPS formats for the patch or provide a v9.1 PLG plugin loader with BPS support
Sorry in advance for the bother

**Comment by leoetlino** [comment]
Well, why not.

You should probably push the authors of those forks to upstream their changes though.

**Comment by ImmortalZypther** [comment]
Thank you so much!

I'll see what I can do, but the PLG plugin loader isn't compatible with v10.0 of Luma (Or nobody has bothered porting it), so the forks might just remain where they are.
