### ISSUE TITLE
[Feature request] Speed modifer for higher frame rate

### ISSUE THREAD

**Issue by FuxorLuck** [leoetlino/project-restoration#104]
Hey
I wanted to ask, are you planning to find the speed modifer of the game?

Hacked versions of citra (liked citra valentine) support costum refresh rate and you can play any game at normal audio speed but higher animation speed so in order to play majoras mask at 60 fps you need speed modifer.

I know that it is really hard to find the speed modifer but you are already work on reverse-engineering the game and you found some modifers already like the deku walking distance

**Comment by leoetlino** [comment]
MM3D is not a variable framerate game, so it would take an insane amount of work to ensure everything works properly at 60fps. That is out of the scope of the project and way too risky to include, sorry.
