### ISSUE TITLE
Free Camera During Zora Swim

### ISSUE THREAD

**Issue by Beldric** [leoetlino/project-restoration#105]
I don't know if this happens with anyone else, but sometimes (More often than not), when I'm Zora Swimming, the camera just stops following the movement of the character, which forces me to change the camera direction every time and it's quite annoying. This made the Race the Beavers side quest a painful and hellish experience. By my experience with the 3D version, the camera did follow the player, which is why I'm guessing it has something to do with the tweaks you made to the free camera mode.
Also, thanks for your hard work, this project is amazing and made me fall in love with the remake again!

**Comment by leoetlino** [comment]
I think you've got things backwards: the camera not following Link after using the free camera is a feature that was already in MM3D. It's working as intended.

Project Restoration actually makes it _possible_ to exit free camera mode when swimming by targeting, which isn't the case in the unmodified version.
