### ISSUE TITLE
Get stock pot inn key without being Goron[Feature request] 

### ISSUE THREAD

**Issue by tstandley** [leoetlino/project-restoration#112]
In the n64 version, you did not need to be Goron link to get the reservation at the stock pot inn. You just needed to ask at the right time. Not sure why they changed it.

**Comment by Luigimeansme** [comment]
They changed it because the one who made the reservation is a Goron, so it makes the most sense for Anju to make the mistake and give the key to another Goron with the same name

**Comment by tstandley** [comment]
She probably gets lots of reservations throughout the year, and there's no reason to assume the reservation was made in person.

In any event, this change makes getting the reservation simply not worth it.

**Comment by Luigimeansme** [comment]
If you're playing Project Restoration, which you obviously are if you're asking this, it takes literally one second to switch to a Goron to get the key. What's the issue?

**Comment by tstandley** [comment]
It's probably just a name in a book, the race probably isn't mentioned.

The problem is that you have to get the Goron mask first, but at that point, the room is not as valuable.

**Comment by leoetlino** [comment]
Hmm, I'm not sure this is worth reverting, given the amount of work that is required (especially when you have to edit message texts for all supported languages) and the fact that you can get the Goron Mask pretty early in a playthrough (as soon as first cycle ends).
