### ISSUE TITLE
Gyorg softlock

### ISSUE THREAD

**Issue by AndrewNDR** [leoetlino/project-restoration#113]
[Citra] About completing the Great Bay Temple, on Gyorg fight, after hitting with the arrows, the games freezes Link like in a cutscene, and all I could do is watch Link rottating on where the boss was.

**Comment by AndrewNDR** [comment]
[Update] Somehow, this issue didn't happened again. I don't know why, but I highly recommend saving before entering the boss door, like I did and stand on a ledge while shooting Gyorg on phase 1.

**Comment by AndrewNDR** [comment]
Sorry, I'll let this open and let you close this, since it may happens to another person.

**Comment by frutch** [comment]
I don't have any cutscene glitch at all, but my game crashes in the 2nd phase, when I hit him with the B button after swallowing a bomb. Happened two times in a row. I guess I have to kill him with the R Button to get forward.
