### ISSUE TITLE
[Feature request] This for OoT?

### ISSUE THREAD

**Issue by Pankeko** [leoetlino/project-restoration#114]
I love this project and all the work you've done my dude, I know you're human and it's really out of scope but, I'd love to see something like this for Ocarina of Time, mainly the QoL controls, holding R and able to select those 2 other buttons and all that. maybe even camera control with the other stick, the faster aiming and all that. 

I'm pretty sure it would be a hard task to do it or time consuming, so I'm just giving this idea out.

**Comment by leoetlino** [comment]
I did consider working on OoT3D some months ago (and in fact this is not the first time I've been asked whether I had any plans for OoT), but unfortunately I don't really have enough free time to work on that...
