### ISSUE TITLE
[Feature request] Inverted y-axis for zora swimming

### ISSUE THREAD

**Issue by tstandley** [leoetlino/project-restoration#115]
I got used to zora swimming on the n64 version, in which the yaxis is inverted. Aiming too. There is a toggle to change aiming, but unfortunately this didn't translate to zora swimming. Thus swimming was really difficult for me so it took like a day to retrain myself to beat the beavers. Then I realized that my aiming intuition was all messed up and I had to switch back to the default aiming behavior, which I still needed to practice.

It would be really nice if zora swimming obeyed the same toggle as aiming so that I would not have had to retrain myself so many times.

**Comment by leoetlino** [comment]
Fortunately, there is also a toggle for swimming (on page 2):

https://www.gameskinny.com/oj22p/majoras-mask-3d-guide-how-to-change-zora-swimming-controls-and-beat-the-beaver-brothers
