### ISSUE TITLE
[Feature request] Make bombers never chase you

### ISSUE THREAD

**Issue by DelusionalDeku** [leoetlino/project-restoration#116]
The bombers already don't chase you when you're wearing a transformation mask, so would it be possible for them to chase chase you under no circumstances?

**Comment by leoetlino** [comment]
Possible, but I think I would prefer to keep it as is. Since MM3D doesn't have BotW-style "near" dialog (messages that show up when you're close to the NPC) chasing the player is the only way they have to let you know that there is a hint available.

**Comment by DelusionalDeku** [comment]
> chasing the player is the only way they have to let you know that there is a hint available.

Wait, do they only chase you when there's an available hint? I can't remember

**Comment by leoetlino** [comment]
Yes
