### ISSUE TITLE
[Feature request] Make red Twinmold always take 2 cycles

### ISSUE THREAD

**Issue by DelusionalDeku** [leoetlino/project-restoration#117]
For whatever reason, you can skip a cycle by rotating the control stick while giant Link is spinning or choking red Twinmold. This makes it so you can defeat red Twinmold in a single cycle and completely trivializes the latter half of the boss fight for no reason.

**Comment by leoetlino** [comment]
Yes, that's intended in the current version.

https://github.com/leoetlino/project-restoration/blob/bdf49ca350093555ca716d0adb99b3cfc8e05d53/source/rst/fixes/boss.cpp#L352-L368

The cycle skip logic was added by Grezzo, not by me. Maybe that decision should be revisited?
