### ISSUE TITLE
Fast Elegy of Emptiness

### ISSUE THREAD

**Issue by leoetlino** [leoetlino/project-restoration#12]
The cutscene that plays after triggering the Elegy of Emptiness should be removed after it's been played once (for each form?) because the player is required to play it many times for the Stone Tower and it quickly gets tiring.

**Comment by bl4zerp** [comment]
could it be possible to skip the song animation by pressing a button?
in a similar way to the mask transformation.

**Comment by leoetlino** [comment]
Possibly, if I figure out how cutscene skipping works. Related to #13

**Comment by leoetlino** [comment]
Looks like the concept of system cutscenes/demos (BotW-style) doesn't even exist in MM... Transformation cutscene is implemented with a bunch of hardcoded code with its own skip logic, and Song of Soaring with another... etc. Skipping isn't implemented at the level of the event system, unlike in BotW, so #13 doesn't actually help with this. :/

**Comment by Luigimeansme** [comment]
Are you doing this Wind Waker HD style where the scene that replays the song is cut out after the first time, or making it so you skip the animation of the statue appearing? Cause you can already skip the statue animation by pressing A

**Comment by leoetlino** [comment]
Skip the song replay, which is the slowest part
