### ISSUE TITLE
[Feature request]  Move Shiro the injured soldier back to Ikana Canyon.

### ISSUE THREAD

**Issue by Jirb** [leoetlino/project-restoration#121]
In MM3D Shiro, the injured invisible guard who gives you the Stone Mask, was moved from Ikana Canyon to the Pirate's Fortress, right where the mask is most useful.

I think this change removed some of the novelty the mask had and makes it feel less like a reward for going out of your way to explore.

I feel like changing this back fits perfectly within the scope of this project.

**Comment by Jirb** [comment]
Accidentally clicked post in the middle of typing this out.

**Comment by Jirb** [comment]
I misclicked a bunch so sorry for the mess.

**Comment by leoetlino** [comment]
No worries. But this is a duplicate of #81 so I'll close this issue.
