### ISSUE TITLE
[Feature request] Auto cancel elegy animation and remove dark filter

### ISSUE THREAD

**Issue by DelusionalDeku** [leoetlino/project-restoration#123]
I think it would be beneficial to automatically give control back to Link while the statue is materializing, since there isn't any indication that you can cancel it with B. (I personally went all the way to stone tower temple before realizing that.)
Another strange thing is that if you do cancel it, the dark fog filter thing is still active, making it impossible to see anything more than 5 feet away from you, and is generally just very strange.

**Comment by leoetlino** [comment]
Skipping the mini cutscene makes sense, I guess.

I've decided to leave the dark effect as is though, as it's the only indicator that the statue is spawning and I don't think it's worth removing it.

**Comment by leoetlino** [comment]
So I ended up making further tweaks to the statue mechanic and getting rid of the dark effect, because now you only get control after the statue has started spawning (to prevent accidentally stepping off the floor switches and triggering too many cutscenes in Stone Tower)
