### ISSUE TITLE
[Feature request] Fix Jim's dialogue to fit new controls.

### ISSUE THREAD

**Issue by Jirb** [leoetlino/project-restoration#125]
I noticed that Jim(red bandana bomber) still tells you to open the Bomber's Notebook with Start instead of Select. Currently I cannot think of any other instance where something like this happens but if it does it would be nice to see that fixed in addition to Jim's dialogue.

I also the think it would be quite nice if there were some sort of ingame tutorial for the new controls if it would be possible to make such a thing.

**Comment by leoetlino** [comment]
Yeah, the Bombers still tell you to open the notebook with START. That's why 1.5.6 moves the notebook back to the START button. I'll close this after 1.5.6 is released.

**Comment by leoetlino** [comment]
https://github.com/leoetlino/project-restoration/releases/tag/v1.5.6
