### ISSUE TITLE
Instructions on the website for Citra should include a mention to manually set the console region; also some sort of visual indicator on 1.0 games that the mod is active

### ISSUE THREAD

**Issue by NintendoManiac64** [leoetlino/project-restoration#126]
I was having a heck of a time trying to get this to work on Citra despite following the instructions and all when it turns out that all I had to do was change the emulation "Region" setting from 'Auto-select' to 'USA'.

This seems like a somewhat important thing to be missing from the instructions (though obviously the emulation region setting shouldn't just blindly be set to "USA" but rather to whatever region your copy of MM3D is).

Also during my troubles, I couldn't help but notice there wasn't really any obvious indicator that the patch was even working if you don't have any existing save data nor if the v1.1 update wasn't installed (with 1.1 it's obvious if the patch is working because the "1.1" indicator on the title goes away).  And even with a new game save when played up until I was a Deku Scrub and walked around a bit, I was somewhat questioning if I wasn't just experiencing a placebo effect in terms of Deku-Link's walking acceleration being altered or not.

**Comment by leoetlino** [comment]
Hm, I've never had to set the region setting to anything other than Auto-select... Either Citra's region auto-detection broke at some point (unlikely though because it's still working for me), or the dump you are using has invalid region lockout data, which causes Citra to misdetect the region.

Does the game work when you remove the patch and set the region setting to Auto-select?

**Comment by leoetlino** [comment]
>...ok this is weird; setting the region to auto-select now results in the patch working. Maybe it's something with v1.0 without the update?

EUR v1.0 works for me without having to set the region, so I don't know :/

I'd suggest asking in the Citra forums (or Discord?) -- maybe someone there can explain why setting the region is necessary but only without the update...

**Comment by NintendoManiac64** [comment]
Regarding the recent commit making mention of setting the region in Citra, I wasn't having crashing issues, rather I was just having issues with the patch actually being active - that is, it would simply run the vanilla unmodded game instead.
