### ISSUE TITLE
Notebook softlock - 1.5.7 

### ISSUE THREAD

**Issue by Anonymine** [leoetlino/project-restoration#129]
(Apologies in advance for the crappy video evidence - I don’t have a capture card)

The addition of the “Select” button as a means of accessing the map in the bomber’s notebook means that you can now open up said map while your notebook is being closed. From here, reopening the bomber’s notebook displays a white screen & softlocks the game. 

Crappy video showing this off below:

https://youtu.be/mlGgRuAS0fw

**Comment by leoetlino** [comment]
Thanks for the report! I'll make a new release, I guess.
