### ISSUE TITLE
Skip animation using Dpad mask buttons

### ISSUE THREAD

**Issue by User220N** [leoetlino/project-restoration#13]
By using the Deku/Goron/Zor masks in the normal buttons (X, Y, I & II), you can press the same button again (or A/B) to skip the animation.
This behaviour does not occur by using the Dpad mask buttons. It is more of a QoL improvement rather than an issue.

**Comment by leoetlino** [comment]
Um, you mean the mask transformation cutscene?

**Comment by User220N** [comment]
> Um, you mean the mask transformation cutscene?

Yes!

**Comment by leoetlino** [comment]
That's quite strange... I'm able to skip the cutscene just fine. https://www.youtube.com/watch?v=awrgf2Z8czU

**Comment by User220N** [comment]
But does it skip the cutscene with the Dpad? I can only skip it with A or B.
I have realised I may have problems with those buttons though.
https://www.youtube.com/watch?v=O4RV33tCUHk

**Comment by leoetlino** [comment]
Ohh, I see what you mean now; you want the D-Pad buttons to also skip the cutscene. That sounds a bit hard as I don't understand how the cutscene code works or where the skip trigger is. I'll leave this open and tag this as enhancement, then.

**Comment by User220N** [comment]
My bad! I should have explained it better from the beginning...
Anyway, thank you a lot!
