### ISSUE TITLE
[Feature request] Fix Deku Lily Pad Hopping

### ISSUE THREAD

**Issue by MarcoDotIO** [leoetlino/project-restoration#132]
**Description**
Since in the 3D remake, lily pad hopping is completely broken. This is because the hops were shortened, along with having any momentum lost when starting the hops. Perhaps add in an additional hop, or lengthen the hopping distance for every hop.

**Comment by SamuelTheSuperb** [comment]
This was already fixed, I believe.

**Comment by MarcoDotIO** [comment]
> This was already fixed, I believe.

Have the mod developers addressed this issue directly?

**Comment by leoetlino** [comment]
This has been fixed even before the first release of Project Restoration, and has been in every version of Project Restoration ^^

**Comment by MarcoDotIO** [comment]
I also have to ask one additional thing while you're here, have you seen[this video](https://www.youtube.com/watch?v=653wuaP0wzs)? It's where I made this issue from. Has this patch addressed those problems presented in the video outside of the deku lily pad hopping?

**Comment by leoetlino** [comment]
The official website (https://restoration.zora.re) has a complete list of features and changes.
