### ISSUE TITLE
Remove a boulder from the twinmold fight 

### ISSUE THREAD

**Issue by Anonymine** [leoetlino/project-restoration#134]
As it now only takes 2 giant’s mask phases to down Twinmold, this completely obsoletes the need for punching - as a wide variety of improvements have been made in that department, I see no point in having a second boulder & believe that one should suffice considering how trivialized the fight has become by having two.

**Comment by leoetlino** [comment]
That would require you to know that the boulder is mostly only useful for Red Twinmold, to have accurate aim, and to not waste it on anything else, considering that boulders do not respawn... On the other hand, having two boulders lets you experiment more and rewards players who can throw things correctly. So I think I'd prefer to keep things as is.
