### ISSUE TITLE
the time bar is not improved with the game in Italian

### ISSUE THREAD

**Issue by HighPingTek** [leoetlino/project-restoration#135]
I don't know if it is right to post the bug here, but with the game in Italian the time bar is not in HD

https://imgur.com/undefined

**Comment by HighPingTek** [comment]
https://i.imgur.com/KGrXHPN.png

**Comment by leoetlino** [comment]
Yeah, the game uses the same texture for things that are locale-specific (action button texts) and things that aren't, as you can see here:

https://zora.re/dl/tex1_512x256_E2CEBCB19DA2608F_13.png

I can edit the other layouts to force using the HD texture, I guess.

**Comment by HighPingTek** [comment]
thanks, I will wait for the new version to play

**Comment by leoetlino** [comment]
Should be fixed with [the `1.5.8-20 + HD HUD` build](https://restoration.zora.re/hd-hud) (refresh the page if you don't see 1.5.8-20). Make sure you update both the code.bps/exheader.bin AND the layout archive, or the game will crash.
