### ISSUE TITLE
Citra crash on in-game save file loading

### ISSUE THREAD

**Issue by cfhull** [leoetlino/project-restoration#137]
**Describe the bug**
Games freezes on black screen when loading save from in game.
Game loads when loading from Citra state, but project restoration is not loaded
Citra log has `HW.Memory <Error>` repeated to infinity

**To Reproduce**
1. Load Majora's Mask v1.1 and Project Restoration v101 on a Citra Canary build OR Majora's Mask v1.0 and Project Restoration v100
2. Load existing Majora's Mask save file through the game menu
3. Screen is black and Citra stops responding

**Additional context**
My core issue is trying to get Project Restoration to load into my existing game. I get the chime when starting the game, but loading from a Citra save state does not seem to apply the mod (select does not open items menu, d-pad doesn't handle masks, none of the other control hotkeys work, etc.). 

I thought it might be necessary to load the game directly through the game menu instead of a Citra save state, but I get the above error.

No difference when switching Citra regions.

Removing the code.bps and exheader.bin from Citra causes loading to behave as normal again, which leads me to believe it's an issue with on the project-restoration side rather than Citra or the ROM

**Comment by axle4222** [comment]
did you try 110?  v100 and v101 are mainly for the Majora's Mask v1.0.  When installing mine I mistakenly thought it was 1.1 and used 110 and had a similar experience to you but after switching to v100 it worked flawlessly.

Short version: try using the v110 files instead

**Comment by leoetlino** [comment]
Another question: Are you using the HD HUD mod? If so, make sure you have also set up the layout archive correctly.

> I thought it might be necessary to load the game directly through the game menu instead of a Citra save state

Correct. Save states include the game's executable code.

**Comment by cfhull** [comment]
> Another question: Are you using the HD HUD mod? If so, make sure you have also set up the layout archive correctly.
> 

That was the issue. While trying to resolve this, I wanted to remove the HUD mod to narrow down the issue, but I had only removed the textures from the custom textures folder and had forgotten that it uses a special version of Project Restoration. Switching back to the regular version of Project restoration solved the problem.

This is a somewhat different issue now, but I don't understand the steps for the HD HUD mod

![image](https://user-images.githubusercontent.com/5115526/82692132-25365300-9c2d-11ea-837a-c18e4f53a5a0.png)

If I simply, load the regular version of Project Restoration and put the MM3DHD textures in, both seem to be working correctly. Are these 6 steps only relevant if I'm using the provided texture file in step 5, and not MM3DHD? If I don't need it, then great, I've succeeded!

If I follow steps 1-6, I get a black screen when loading a save, with either the provided texture file, saved as a .png directly in the textures folder or with MM3DHD instead. I extracted the layout folder directly into the mods folder, so that there are no folders, only 5 sibling files.

**Comment by leoetlino** [comment]
Those steps are required if you want to get the new HUD on the main screen.

When you click on *Open Mods Location* for MM3D, what do you see? There should be a "romfs" folder.

**Comment by cfhull** [comment]
🤦 That's how I originally had it but since things weren't working right I thought maybe I needed to pull out the files since the steps specifically said `the layout archive` which is the name of the subfolder. Putting the whole romfs folder in the mods directory and switching to the special version of Project Restoration is working now.

I didn't realize the HUD Mod added things like the D-Pad mask UI. I assumed it was something that MM3DHD was a replacement for.

At the end of the day, after fiddling with everything, my core problem was that I had missed that the layout archive needed to be extracted to the mods folder, not the textures folder. Using the special version of project restoration breaks if that file is missing like you said.

Everything is working now, and I appreciate your help!

**Comment by leoetlino** [comment]
Glad to hear it's working now! I'll leave this issue open because Project Restoration should probably tell you that the files are set up incorrectly instead of crashing.

**Comment by leoetlino** [comment]
For simplicity and technical reasons, I've decided to not show an error message in-game. Instead I've updated the HD HUD page to clarify the instructions and add a new troubleshooting section. Hope this makes things clearer.
