### ISSUE TITLE
Once you press ZR it becomes toggled permanently and is now inverted.

### ISSUE THREAD

**Issue by axle4222** [leoetlino/project-restoration#139]
**Describe the bug**
When playing the game once you press ZR for the first time it permanently toggles it.  What I mean by this is that it does what was intended and shows I and II item slots and replaces A with the ocarina shortcut.  However it stays that way even after releasing the button.  It becomes inverted where you have to press ZR to do the opposite and it goes right back to I and II with ocarina being on A.  I checked the page home page of Project Restoration and the home page describes it as exactly the opposite. This makes it slightly tedious to roll or interact with the environment. this bug also apparently affects playing the ocarina as when I start playing once I let go of ZR it begins to constantly play R. This makes the ocarina unplayable once the bug is established.  Before the bug it plays perfectly fine so it is not a controller issue.

**To Reproduce**
This has happened for both me and my friend who I guided through the installation process:  Start up Citra, open Majora's Mask and your save, play like normal until you press ZR and it does the aforementioned bug

**Screenshots**
![image](https://user-images.githubusercontent.com/65749489/82629285-cf25c900-9bb4-11ea-95db-804247c9ff6f.png)

![image](https://user-images.githubusercontent.com/65749489/82629293-d51baa00-9bb4-11ea-963d-f9d707d9809f.png)

**Additional context**
I have attempted three separate fresh installations. the original, the one for my friend, and the current build.

**Comment by axle4222** [comment]
I should probably leave the build: 1.5.8-5 the one for the HD UI

**Comment by tree-frog** [comment]
I had the same issue using an Xbox One controller & it was a Citra configuration issue caused by how it handles the digital left/right triggers. Very frustrating, but nothing to do with Project Restoration.

When mapping the controller, first hold down the LT/RT on the controller, then click the mapping text field in Citra, then release the trigger. If done correctly, the mapping should read something like "Axis 5+".

**Comment by axle4222** [comment]
That was definitely it thank you guys so much!
