### ISSUE TITLE
Doesn't patch

### ISSUE THREAD

**Issue by DitDitGitHub** [leoetlino/project-restoration#14]
I have installed the Luma3DS fork and have put the files in luma/titles/0004000000125600 (I am using the EUR version). I have enabled game patching in the Luma settings (select at boot) but still there is no difference. I have tried every version (v100, v101, v110) and... nothing. I'm not using a Game Cart, I have the game digitally downloaded and I have the update installed.

**Comment by leoetlino** [comment]
Just to be sure, you have /luma/titles/0004000000125600/code.ips and /luma/titles/0004000000125600/exheader.bin on your SD card, correct?

**Comment by DitDitGitHub** [comment]
Well, I'm currently using v110, so .bps, but yes

**Comment by leoetlino** [comment]
Hm, strange. Try putting the v100 files in /luma/titles/0004000000125500 just in case, as it sounds like Luma can't even find the patch files (otherwise it'd have at least crashed once).

**Comment by DitDitGitHub** [comment]
> Hm, strange. Try putting the v100 files in /luma/titles/0004000000125500 just in case, as it sounds like Luma can't even find the patch files (otherwise it'd have at least crashed once).

Hmm... okay

**Comment by DitDitGitHub** [comment]
Still doesn't work

**Comment by DitDitGitHub** [comment]
Could you post a .zip file with the EXACT file names and stuff, so I am sure that I've got it right.

**Comment by leoetlino** [comment]
[sd.zip](https://github.com/leoetlino/project-restoration/files/3398832/sd.zip)

**Comment by ClunkyClanky** [comment]
Hey @DitDitGitHub I had the same problem as u I have the Eur version like u and it s on the 1.1 update so I assumed I had to use the files found in the 110 folder but that gave me a axception has occured error so then when I saw leoetlino point out the game having 1.0 or maybe 1.1 preloaded I remembered that mine was installed in 1.0 then I updated it manualy so I tried the files on the 100 folder which include an ips file and the '' exheader_legacy '' which u have to rename into '' exheader '' and it worked and I no longer get the error 

Just delete all the files in the TID and try this again with just the files from 100 folder and copy the ips file to luma/titles/0004000000125600 then copy the '' exheader_legacy '' to same directory and rename it to just '' exheader '' 

Also make sure the game patching is activated 

It worked for me 
I think we had the exact same problem

**Comment by DitDitGitHub** [comment]
I didn't have the same problem @ClunkyClanky, it's just that I hadn't installed the edited Luma3DS properly. Can I recommend @leoetlino to add in the guide to copy the boot.firm to the CTR NAND using godmode9 as well as in the SD?

**Comment by leoetlino** [comment]
Oh, I see. I've updated the instructions. Happy to hear you got it working :)

**Comment by Daddu3** [comment]
Heyy -

Been trying every one of the suggestions and options to make the patch work - including copying the SD-contents from @leo and installing the boot-firm to CTRNAND - but I keep still getting this exception error:

Processor: ARM11 (core 1)
Exception type: prefetch abort (svcBreak)
Fault status: Debug event
Current process: loader (0000000000000000)

Using EU-version with 1.1 on, and tested with all versions.

**Comment by leoetlino** [comment]
svcBreak likely means you aren't using the right patch. Are you sure you really tested all three patches (v100, v101, v110) and deleted code.ips/code.bps between each attempt?

**Comment by Daddu3** [comment]
> svcBreak likely means you aren't using the right patch. Are you sure you really tested all three patches (v100, v101, v110) and deleted code.ips/code.bps between each attempt?

Re-tried now, also downloaded the Boot.firm you linked to and pasted on CTR-NAND again. 

V.100 now works - unfortunately I can't just use the toggling between Zora Fast Swim/Slow Swim via D-Pad for now though, so got to hold the ZL-Button for that. Is the toggling not implemented on V.100?

**Comment by leoetlino** [comment]
v100 isn't the Project Restoration version number, but the version of MM3D the patch targets. So for example v100 is meant to be used with MM3D 1.0, v101 with MM3D 1.1 (variant A), v110 with MM3D 1.1 (variant B). Usually, v100 is the right version to use if you don't have a game card that came with the 1.1 update.

Toggling isn't implemented in Project Restoration 1.3.0, but will be part of the upcoming release (1.4.0). Here's a build that includes the toggle feature: https://static.zeldamods.org/mm3d/mm3d_project_restoration_v1.3.0-3-gdba2efc.7z

**Comment by Daddu3** [comment]
> v100 isn't the Project Restoration version number, but the version of MM3D the patch targets. So for example v100 is meant to be used with MM3D 1.0, v101 with MM3D 1.1 (variant A), v110 with MM3D 1.1 (variant B). Usually, v100 is the right version to use if you don't have a game card that came with the 1.1 update.
> 
> Toggling isn't implemented in Project Restoration 1.3.0, but will be part of the upcoming release (1.4.0). Here's a build that includes the toggle feature: https://static.zeldamods.org/mm3d/mm3d_project_restoration_v1.3.0-3-gdba2efc.7z

Aaah, alright then. Thanks for providing!
