### ISSUE TITLE
[Feature Request] Optional Song of Inverse Time Nerf

### ISSUE THREAD

**Issue by Fijiboy99** [leoetlino/project-restoration#141]
**Please ensure the feature or the change you're suggesting isn't out of the scope of this project. In most cases, only bug fixes, beneficial MM3D change reversals or QoL improvements will be accepted.**

**Description**
A clear and concise description of the suggested changes.

**Additional context**

**Comment by leoetlino** [comment]
Maybe in a hero mode mod.

**Comment by Fijiboy99** [comment]
That's weird, it erased what I wrote for the description and additional context.

I don't feel like rewriting everything I wrote before, but the reason I asked for it was that I felt the song of inverse time was always too powerful in the original, and while I love everything else this patch changes, I actually felt the song of time nerf was the one good change the remake made, and I wished there was a way to play this mod with that still in tact.
