### ISSUE TITLE
[Feature request] 

### ISSUE THREAD

**Issue by wad11656** [leoetlino/project-restoration#144]
Can I use the .cia rebuild tool to hard-code your patch files into the .cia?
https://gbatemp.net/threads/tutorial-how-to-decrypt-extract-rebuild-3ds-cia-cxi-files.383055/

When I extracted my .cia, I didn't see the files your patch provided so that I could replace them.

Also, I want to get rid of the "This game has an update" notifications on the 3DS Home screen for this game. I think rebuilding the .cia while specifying "minor" and/or "micro" version numbers would help with that. Do you know which "minor" and "micro" version #'s I'd use when rebuilding the .cia to get rid of Update notifications?

**Comment by leoetlino** [comment]
For questions, please ask in this Discord server: https://discord.gg/h2p8GWm

(Issues and replies send a notification to everyone who is watching this repo...)
