### ISSUE TITLE
Citra: Game freezes following the intro cutscene. 

### ISSUE THREAD

**Issue by pullen8** [leoetlino/project-restoration#147]
When Skull Kid steals Epona and the game fades to gray, Citra freezes and attempting to exit emulation causes a crash. The vanilla game works fine and the mod is installed correctly.

**Comment by leoetlino** [comment]
Are you using the [HD HUD mod](https://restoration.zora.re/hd-hud)? If so, can you make sure you have set up the layout archive correctly (step 2)? I'll close this for the meantime because this is very likely to be a setup issue.

**Comment by boyooo** [comment]
This is happening to me

**Comment by phly95** [comment]
> This is happening to me

Happened to me too. It was because I put the joker files directly in the mods folder. You need there to be a romfs folder inside of the mods folder.
