### ISSUE TITLE
Can I have a more in depth tutorial on this mod?

### ISSUE THREAD

**Issue by babiesthealer** [leoetlino/project-restoration#148]
I have no idea where or what code.bps or exheader.bin is. I looked at the tutorial on the website with no idea what to do.
This is the tutorial that I'm referring to: 
Right-click on the game in the game list and select Open Mods Location.
Copy code.bps to that directory.
Copy exheader.bin to that directory. 

I'm using Citra Canary, and I'm not familiar with adding mods to roms

**Comment by leoetlino** [comment]
code.bps and exheader.bin are in each of the v100/v101/v110 folders. And you can get those folders by downloading the release 7-Zip archive (using the big download button on the website).

I recommend reading the instructions again very carefully. It sounds like you've skipped straight to the Citra instructions, even though *everything* on the website is important.
