### ISSUE TITLE
Fix non-grabbable ledge in Snowhead Temple

### ISSUE THREAD

**Issue by ad1217** [leoetlino/project-restoration#15]
Not sure how possible this is, but it would be great to fix the non-grabbable ledge for a stray fairy in Snowhead Temple, as per https://youtu.be/653wuaP0wzs?t=1162.

**Comment by leoetlino** [comment]
Can't fix this without model and collision editing, which makes this... rather difficult.

**Comment by nr1995** [comment]
I know this probably won't make anyone feel any better,
but many have been led to believe that you can only get that fairy now,
by hopping in a Deku flower and floating down for like a minute or something.
No!  Nerrel's wrong on this one.
You can jump directly to it with regular Link without needing the edge at all.
I did it first try.

**Comment by ad1217** [comment]
I just tested, and you can get to this fairy by just normally jumping from the top level of Snowhead Temple. While somewhat annoying, this is certainly not as big of an issue as portrayed in that video. I'm not convinced that this is actually worth patching.
