### ISSUE TITLE
(Feature Request) fix the Snowhead Temple fairy chest ledge

### ISSUE THREAD

**Issue by SVM78** [leoetlino/project-restoration#152]
There's a ledge in Snowhead Temple you need to fall onto to get a stray fairy. However in the remake the ledge was made ungrabbable, meaning you currently have to slowly fall down as a Deku and waste a lot of time.

**Comment by KingLuigi128** [comment]
Nerrel was wrong about that, Deku _isn't_ the only way to reach that fairy.
(Also I'm fairly certain that that ledge was _always_ ungrabbable...)
Besides this topic was brought up ages ago (#15), no need for a repeat.
