### ISSUE TITLE
Inverted Song of Time un-nerf does not apply for a in-game hour

### ISSUE THREAD

**Issue by FumiKane** [leoetlino/project-restoration#159]
Inverted Song of TIme has 1/3 slowdown of time in N64 nd 1/2 slowdown of time in vanilla MM3D. In the patch it supposely reverts it to 1/3 but I noticed that from 6:00 AM 1st day to 7:00 1st day it is 1/2.

Saved to an owl statue after 7:00, turned off game and loaded, patch applies 1/3 as expected.

I will try to replicate and record a comparison, directly compared it to N64 and after 7:00 it applied the un-nerfed slowdown. Will see if it happens at other times in-game.

**Comment by leoetlino** [comment]
Yes, the slowdown is only 1/2 in some situations (e.g. when Kafei is visible):

https://github.com/leoetlino/project-restoration/blob/fbd85ca96037c13b4515fa1477393f3ddd784948/source/rst/fixes/time.cpp#L17-L44

The 1/3 slowdown breaks some aspect of Kafei's actor. I don't remember what exactly was broken, but it must have been severe enough to warrant temporarily disabling the un-nerf...
