### ISSUE TITLE
Crash on launch - An exception occurred

### ISSUE THREAD

**Issue by N8pC5U012G7bjT** [leoetlino/project-restoration#161]
**Describe the bug**
I get an "An exception occurred" error on launch

**To Reproduce**
My system is an outlier but I suspect it's due to being a Japanese system with a CTRTransfer to English.
So have my system and try and launch the game after setting up the Titleid folder and v100 of the patch.

**Screenshots**
![IMG_20201114_192707](https://user-images.githubusercontent.com/74480133/99162194-d33c2a80-26af-11eb-913e-1dffd08d26e9.jpg)

**Additional context**
As I mentioned my console has had its region changed from Japan to USA. I have a second 3DS to test on, both are newly setup, completely up to date with the latest Luma v10.2 and BS9. The other one is a native USA 3DSXL and using the USA TitleID and v100 patch works just fine. The only difference is that mine was a native Japanese 3DSLL that I CTRTransfered to English.

Here's some crash dump it gave, I hope they help. They should all be the same.
[Crash Dumps.zip](https://github.com/leoetlino/project-restoration/files/5541806/Crash.Dumps.zip)

**Comment by Casuallynoted** [comment]
I'm having the exact same issue on mine. Same region change, same everything. Was this ever fixed, @N8pC5U012G7bjT ?
