### ISSUE TITLE
[Feature Request] Make “Start” open up Item screen in Zelda: Ocarina of Time 3DS

### ISSUE THREAD

**Issue by MarioKartFan** [leoetlino/project-restoration#165]
This patch is incredible, and it makes Majora’s Mask 3DS the ultimate version of the game.  While you included many quality of life improvements, the one that I miss the most in the other Zelda 3DS is the ability to call up the Item Screen using the “Start” button.  Why on Earth Greezo thought that we needed both Select and Start to pull up the save screen is beyond me.

**Comment by leoetlino** [comment]
Thanks for your kind words. This project is only about Majora's Mask 3D, though.
