### ISSUE TITLE
Softlock on hitting Southern swamp owl statue with sword

### ISSUE THREAD

**Issue by FormlessManager** [leoetlino/project-restoration#167]

**Comment by FormlessManager** [comment]
The game softlocked for me after hitting the southern swamp owl statue. I had just obtained the song of soaring as deku, turned back into human,  and hit the statue, the camera turned to face link and the game became unresponsive.

**Comment by fpi1337** [comment]
I was interested in this issue as well when I read this. I tried it for myself and I did NOT experience this under Citra. Maybe this error only persist on the Nintendo 3DS or for a different game version? Mine seems to be the PAL 1.0 version. So, no issues. I thought this information could help.

**Comment by Etsamaru** [comment]
> I was interested in this issue as well when I read this. I tried it for myself and I did NOT experience this under Citra. Maybe this error only persist on the Nintendo 3DS or for a different game version? Mine seems to be the PAL 1.0 version. So, no issues. I thought this information could help.

I did this on Citra just yesterday and it in fact happened to me too exactly as the previous poster said. I didn't realize it was caused by this but it was the exact situation during the soufhrlern swamp.

**Comment by leoetlino** [comment]
Unfortunately I've been unable to reproduce this bug... if anyone manages to trigger it consistently and can post a video of the glitch, that'd be much appreciated!

**Comment by fpi1337** [comment]
> > I was interested in this issue as well when I read this. I tried it for myself and I did NOT experience this under Citra. Maybe this error only persist on the Nintendo 3DS or for a different game version? Mine seems to be the PAL 1.0 version. So, no issues. I thought this information could help.
> 
> I did this on Citra just yesterday and it in fact happened to me too exactly as the previous poster said. I didn't realize it was caused by this but it was the exact situation during the soufhrlern swamp.

Pretty interesting. Which game version do you have? Weirdly I can't reproduce it either. :-/ However if that happens to other people, it really is an important bug.

**Comment by Etsamaru** [comment]
> Unfortunately I've been unable to reproduce this bug... if anyone manages to trigger it consistently and can post a video of the glitch, that'd be much appreciated!

I got it on the second try, haven't done it a third time yet.

https://www.youtube.com/watch?v=mmm3zPXZNQY

**Comment by Etsamaru** [comment]
> > > I was interested in this issue as well when I read this. I tried it for myself and I did NOT experience this under Citra. Maybe this error only persist on the Nintendo 3DS or for a different game version? Mine seems to be the PAL 1.0 version. So, no issues. I thought this information could help.
> > 
> > 
> > I did this on Citra just yesterday and it in fact happened to me too exactly as the previous poster said. I didn't realize it was caused by this but it was the exact situation during the soufhrlern swamp.
> 
> Pretty interesting. Which game version do you have? Weirdly I can't reproduce it either. :-/ However if that happens to other people, it really is an important bug.

I have been able to reproduce it by pulling out the ocarina and hitting the sword button out of it, I've done it a few times in a row.

https://user-images.githubusercontent.com/61356819/129103184-98a4ca30-7952-4f7d-a528-f45c6fc11957.mp4

**Comment by Etsamaru** [comment]
UPDATE: It seems you can do this at any statue, take out your ocarina and then swing your sword. I just did this at woodfall temple's statue.

https://user-images.githubusercontent.com/61356819/129121122-aeb7cc94-d512-4d3e-9868-bd62b6d7e55e.mp4

**Comment by leoetlino** [comment]
Interesting... so it must be some kind of transition issue between the ocarina and the attacking states... I don't really have enough free time to investigate the bug and fix it at the moment but this is really helpful, thanks for figuring out how to repro it consistently!

**Comment by Etsamaru** [comment]
No problem I'm glad that I could help! Everything else seems to be going well, after getting the first clip I decided to keep playing to the temple and decided to try it there to see if it was isolated to that one statue or not. 
Happy to help!

**Comment by fpi1337** [comment]
Very nice! I was also able to reproduce it at any owl statue. However, you can get around this issue if you use a transformation mask after you used your ocarina. This seems to avoid this issue since you can hit the statue with your sword after you transformed back into Link wihtout getting softlocked.
