### ISSUE TITLE
Original Great Fairy Upgrades 

### ISSUE THREAD

**Issue by DeathWrench** [leoetlino/project-restoration#17]
In the original Majora's Mask for collecting all stray fairies in Woodfall you would get the Magic Spin attack. For Snowhead you would get the bigger magic bar.

In the 3ds version they are reversed. Woodfall gives you bigger magic bar and Snowhead gives you Magic Spin Attack.

here is the source: [https://zelda.gamepedia.com/Great_Fairy#Majora.27s_Mask](https://zelda.gamepedia.com/Great_Fairy#Majora.27s_Mask)

**Comment by leoetlino** [comment]
Honestly, I prefer the new upgrade order. Being able to get the larger magic bar earlier is nice.

**Comment by DeathWrench** [comment]
I see how some people may like the new change as well, it is beneficial to not have to turn the fairies in at snowhead. I also see how this could end up requiring double the amount of work, as there would be a division between people that want it and people that don't.
