### ISSUE TITLE
[Feature request] Remove the timer above the screen in the "Count to 10 in Your head" side-quest

### ISSUE THREAD

**Issue by Halzenut15** [leoetlino/project-restoration#175]
in the postman side-quest, where you have to count to 10 to get a heart piece, a timer helping you appears above the screen.
the challenge is for you to count to 10 in your head, but the timer and the clock sounds makes it needlessly easy.

(i don't know if this was already removed... anyways...)

**Comment by Luigimeansme** [comment]
The timer only appears if you wear the bunny hood, and you can mute the game if you don't want to hear the timer. This change is unnecessary

**Comment by Halzenut15** [comment]
oh, sorry, i didn't know about that
