### ISSUE TITLE
Cannot use A button

### ISSUE THREAD

**Issue by ikenjake** [leoetlino/project-restoration#177]
I installed the patch and the HD mods and my A button does not do anything in game. It works in the menu and when loading a game, but once the actual game loads, I cannot open the first door in the game. I genuinely have no idea why this is happening.

I'm using Citra Nightly on a 1.0 version of the game.
![image](https://user-images.githubusercontent.com/3105913/110014898-5500a400-7cf1-11eb-9bba-1908c6982b59.png)

**Comment by ikenjake** [comment]
The button is definitely bound correctly in the emulator it just doesn't actually have a function in the game.

**Comment by ikenjake** [comment]
It's definitely an issue with the HD pack because I got this to work perfectly fine with the normal version

**Comment by DeathWrench** [comment]
The HD pack only replaces texture assets and does not mess with the functionality of the A button whatsoever.

**Comment by jordilaforge** [comment]
project restoration remaps the button. You have to press LR+A to open doors.

**Comment by leoetlino** [comment]
No, you shouldn't have to if your controller bindings are configured correctly.

**Comment by leoetlino** [comment]
Cannot reproduce and this is most likely user error.
