### ISSUE TITLE
[Feature request] [QoL] Having the option to pick and choose the features you want before patching.

### ISSUE THREAD

**Issue by Ardi-san** [leoetlino/project-restoration#182]
I want to be able to disable the features such as "Fixed Zora" and "Fixed Deku" as I personally like those changes but I would love to keep everything else such as Button Tweaks, Fast Transformation and more since they are HUGE QoL features i'd love to play with ingame on Citra. 

I love options. I hope this isn't too much to ask for since you're very far in development.

**Comment by leoetlino** [comment]
Those features can be disabled by modifying the source code directly, but no support will be provided for doing so because this is an opinionated patch (i.e. it reflects my vision of how the game should be).

**Comment by Ardi-san** [comment]
Could you tell me how to disable it within the sourcecode at least??

**Comment by leoetlino** [comment]
I know I said I would not provide any support, but I can provide some pointers, I guess...

https://github.com/leoetlino/project-restoration/blob/b8e56743524be9f5d7a73daea298d6eb04642a38/source/rst/link.cpp#L94

Add "return false;" at the beginning of that function.

https://github.com/leoetlino/project-restoration/blob/b8e56743524be9f5d7a73daea298d6eb04642a38/source/rst/link.cpp#L23-L25

Remove those lines.

**Comment by ProNerdy** [comment]
> I want to be able to disable the features such as "Fixed Zora" and "Fixed Deku" as I personally like those changes but I would love to keep everything else such as Button Tweaks, Fast Transformation and more since they are HUGE QoL features i'd love to play with ingame on Citra.
> 
> I love options. I hope this isn't too much to ask for since you're very far in development.

I just wanted to comment that you can change the Zora swimming speeds by either holding down ZR, or you can toggle the Zora swimming with ZL. There isn't a toggle for Deku hopping, but the faster acceleration of the Deku makes the platforming on Lily Pads a lot more enjoyable in my opinion
