### ISSUE TITLE
Mod Breaks Citra Cheats

### ISSUE THREAD

**Issue by Karma-Fox** [leoetlino/project-restoration#189]
**Describe the bug**
Citra cheats work without issue. Once mod is installed, a lot of cheats no longer work (some still do, though not as many as without mod). This includes the Moon Jump cheat (LR+A).

**To Reproduce**

1. Install mod,
2. Turn on Moon Jump cheat,
3. Try to moon jump.

**Comment by Karma-Fox** [comment]
Never mind. This actually seems to be a bug from the layout file that was linked by HD Hud and not the mod itself.

**Comment by leoetlino** [comment]
This is **not** a bug. Tons of cheats assume that game objects will be located at specific locations in memory. Any cheat that relies on those bad assumptions are bugged and broken.
