### ISSUE TITLE
Unfortunately I've been unable to reproduce this bug... if anyone manages to trigger it consistently and can post a video of the glitch, that'd be much appreciated!

### ISSUE THREAD

**Issue by Etsamaru** [leoetlino/project-restoration#195]
Unfortunately I've been unable to reproduce this bug... if anyone manages to trigger it consistently and can post a video of the glitch, that'd be much appreciated!

_Originally posted by @leoetlino in https://github.com/leoetlino/project-restoration/issues/167#issuecomment-896406994_

I will try to reproduce it tomorrow, I quit right after it happened so I should be able to do the same thing. It was my first time in the swamp after seeing the cutscenes with the skullkid and the fairies for sure. I had streamed it but I deleted the stream. (Of course I would!)

**Comment by fpi1337** [comment]
Appreciate your help with that! This project is too good to maintain an issue like this.
