### ISSUE TITLE
Citra black screen when trying to load .3DS file

### ISSUE THREAD

**Issue by zmarotrix** [leoetlino/project-restoration#21]
I have tried loading vanilla MM3d and it worked fine. When I try to load this mod with Citra 1405-d5e23e0 I get a black screen then the Citra starts to crash. I have tried both loading with the patch in the subfolder and by patching code.bin myself to the same effect.

Edit: I've tested with both 1.3.0 and the beta build you posted on Reddit earlier today. Both have the same result. I'm fairly confident I have MM3D 1.0 because the other 2 patches both gave an error when I tried to patch them onto my code.bin saying it was not made for that file.

**Comment by leoetlino** [comment]
Could you show a screenshot of the folder that contains your .3ds file?

**Comment by zmarotrix** [comment]
https://imgur.com/95tP5iW

**Comment by leoetlino** [comment]
You forgot the exheader.

**Comment by zmarotrix** [comment]
I cannot believe I spent 2 hours doing all this and I just put the exheader in the wrong place.
