### ISSUE TITLE
Infinite loading latest patch version 1.00

### ISSUE THREAD

**Issue by ZombieConker** [leoetlino/project-restoration#211]
**Describe the bug**
Start the game and doesnt boot infinite loading 3ds screen on  new 3ds screen majoras version 1.0.

**FIXED** SIMPLY USE EXHEADER_LEGACY.BIN AND RENAME IT TO EXHEADER.BIN DONT USE THE EXDEADER.BIN ON THE FOLDER!

**Comment by leoetlino** [comment]
Uh, that's not good. Have you tried the previous version (1.5.8)? Does 1.5.8 work?

**Comment by leoetlino** [comment]
Ah, so it turned out to be an exheader issue. Okay, I guess I'll need to rename the files in the archive.

**Comment by ZombieConker** [comment]
Fixed it i just used the wrong header!
