### ISSUE TITLE
[Feature request] it is not a normal request!

### ISSUE THREAD

**Issue by ZombieConker** [leoetlino/project-restoration#212]
Simply your work is just too much good and after you re-added infinite sword glitch it is just a wonderful experience, i combined your work with a remapped control setting that i really wish was by default i found a way to use c stick for the ocarina as a original c button unfortunaly Cant use A but works with the default L button and there is another mod( that dont work with yours) that simple change on screen button of ocarina to original one yellow c button, anyway if you could add an option for that that would be really cool( i did the same in oot 3d and works well and i even mapped all the button ( quick camera quick y and x and even start and screen menu like you did in majoras mask)  but it is not perfect i really want you to do a quality improvement on oot 3d not a full head -on restoration but just a control update and one glitch re added like infinite sword glitch as it would make both game as close to the original so yea a double request and huge wall text but your work is just too much good to leave oot 3d in the dust and perphaps re add c stick ocarina to both like i do thanks you for your hard work and everything you done to the zelda community.

**Comment by leoetlino** [comment]
Thanks for your kind words! Unfortunately I cannot add remapping options because that would be way too complicated to implement as part of the patch and ultimately whatever I implement would be *less* flexible than using control remapping homebrew like [rehid](https://github.com/hax0kartik/rehid). I also do not have time to work on OoT3D, sadly.

**Comment by ZombieConker** [comment]
I see that sad for oot 3d but understandable i wish you a good rest of the holiday and i hope you continue polishing the infinite sword glitch as i think the timing is a little off for bomb hover idk maybe that me but i wasnt able to do them correctly maybe that just my timing but it feel a little different from lets say majoras mask n64 but like i said maybe is just because 20 fps to 30 is playing tricks on my mind haha
