### ISSUE TITLE
Fast Ocarina not working on Citra

### ISSUE THREAD

**Issue by zmarotrix** [leoetlino/project-restoration#22]
I'm running your build from Reddit earlier today on Citra and the Fast Ocarina is not working. Nothing happens when I press ZR.

**Comment by leoetlino** [comment]
Whoops, I forgot to update the documentation... To allow for more fast actions (#16), the Ocarina is now mapped to ZR+A, not just ZR. Sorry about that; I'll update the documentation

**Comment by zmarotrix** [comment]
Did you do something similar to D-pad transformations? Pressing Down does not transform into Deku.

**Comment by leoetlino** [comment]
I didn't
