### ISSUE TITLE
Selectively enable features via compilation flags

### ISSUE THREAD

**Issue by GistOfSpirit** [leoetlino/project-restoration#220]
I think it might be a good idea if people using the mod could enable only specific features. While creating a UI for it would be difficult, perhaps it might be possible to do it with compilation flags, so that people who don't want all the features could (relatively) easily make a customised version of the mod.

**Comment by leoetlino** [comment]
Project Restoration is inherently an opinionated mod, and creating the UI / infrastructure that would allow users to compile custom builds is rather time-consuming. Considering that the mod is already open source, I think this is unlikely to happen and so I am marking this as wontfix to avoid giving you false hopes.
