### ISSUE TITLE
Goron Curl Mode Toggle Toggler

### ISSUE THREAD

**Issue by PRGilland** [leoetlino/project-restoration#23]
In the original N64 version, you had to hold the A button to stay in curl mode and to roll, but in the 3DS version, it toggles curl mode. 

In most circumstances, this change is nice, as you do not have to hold the button down while rolling around. In certain instances, however, such as the cliffs outside Snowhead Temple, being able to stop rolling by letting go of the button would be handy, and is also simply muscle memory from playing the original version. 

May I suggest another quick toggle to toggle the hold and toggle modes, as you did with Zora swimming, maybe default it to the classic mode as well?

**Comment by leoetlino** [comment]
I'd be against changing the default mode, as it seems people like the new mode, but a toggle could be added, I guess. This might be tricky though because we're running out of buttons. (D-Pad Up/Down wouldn't work here as they're used for the Goron Mask/Deku Mask.)

**Comment by conkerbad4day** [comment]
What if yous us zr+ goron mask key(up) you could do the same to toggle zora swim with zr+left and deku speed jump to zr+down

**Comment by bl4zerp** [comment]
I don't think this one is really needed, it was probably changed to free your thumb so you can move the camera, it's not like it breaks anything. I guess it would be nice to give old players the option to play it like in the original but I agree it should not be the default mode.

**Comment by DeathWrench** [comment]
Would there be a way to add settings in the options menu?

**Comment by leoetlino** [comment]
Too complicated.
