### ISSUE TITLE
Softlock when opening "Gear" menu

### ISSUE THREAD

**Issue by macardiel** [leoetlino/project-restoration#230]
Citra Nightly 1784
Majora's Mask v1.0
Project Restoration 1.5.9 - v100

When using the mod, the "Gear" menu softlocks the game. Music continues, game appears to continue to run, but nothing is displayed other than the background.

Before opening "Gear" menu:
![image](https://user-images.githubusercontent.com/25373353/188951208-0496347d-4248-4c41-9dbf-7d96d0bcae86.png)

After opening "Gear" menu:
![image](https://user-images.githubusercontent.com/25373353/188951241-01e81438-c578-4f11-bbb1-d706a9d892a6.png)

**Comment by macardiel** [comment]
Also tested using majora's mask 1.1 update and v100 and v101 of the mod. They all have the same issue and others e.g. v101 will not start the game unless I load a save state.

**Comment by leoetlino** [comment]
Can't reproduce your issue with Majora's Mask 1.0 and Project Restoration 1.5.9 (v100), even on a fresh save.

![mm3d_rst_issue_230_no_repro_1](https://user-images.githubusercontent.com/4209061/194715181-d5caedbb-78ae-4842-988a-c5ab022b40f4.png)
![mm3d_rst_issue_230_no_repro_2](https://user-images.githubusercontent.com/4209061/194715177-f8017a6b-fdb3-4ddd-a3a3-dbfde607371b.png)

It looks like there's something seriously wrong with your game as you are missing the health display on the bottom HUD (you should see 3 hearts in the HUD).

Can you right click on the game in the game list and select *Open Mods Location*, and screenshot the contents of that folder?

**Comment by macardiel** [comment]
Issue was likely my dump as you suggested. It worked fine without the mod but no matter, I never validated the Checksum. New dump works fine with the mod. Thank you!
