### ISSUE TITLE
Please re-write instructions.

### ISSUE THREAD

**Issue by Shituation** [leoetlino/project-restoration#237]
The page is giving messy instructions; for example it first tells you to do X step then between parentheses it gives another link for another purpose making the first step invalid.
I'm following a guide step by step and the next thing is nullifiying the previous one.

FIRST STEP
> For Citra users
> 
> This guide assumes that you know how to use Citra. If this is not the case, refer to the official website for help.
> 
>     Open the citra folder in the 7-Zip archive.
>     Right click on the game in the game list and select Open Mods Location.
>     Copy code.bps and exheader.bin to that directory.   
**- GREAT DONE.**

> Playing at high resolutions? You might want to check out the HD HUD mod.    

FU** 😒. DONE AGAIN.

> 
> Step 2
> 
> Download and extract the layout archive...  

**DONE**

> (**or this one for Xbox controller users**).... [...]

 
🤦‍♂️

> Step 3
> 
> Right click on the game in the Citra game list and select Open Custom Texture Location.
> 
> Download **this texture** and put it there.
> 
> Enable custom textures in Citra (Emulation → Configure... → Graphics → Use Custom Textures).
> 

**DONE**

> Optional but highly recommended: 
_download this HD texture pack and extract it in the Custom Texture Location_. The textures come from the MM3DHD project and currently cover almost all of the game menus and Link's forms!
>
 🤬🤬🤬
PS: that "HD texture pack" is asking me to replace the file that you made me download and put into textures folder.
What do I do with these folders from that pack?
![2](https://user-images.githubusercontent.com/43975882/207669637-9df16b8d-eb2d-4a70-a8ed-1835f9308f83.jpg)

![1](https://user-images.githubusercontent.com/43975882/207669646-e0159811-804a-4776-bd8c-901f2b84f8d6.jpg)

> 
> If you've followed the instructions correctly, you should see code.bps, exheader.bin and romfs (folder) in the Mods Location.

**NO, I ended up with "romfs" AND "Project Restoration UI" folders inside mods folder because I need xbox layout. Is this wrong? the guide doesn't mention it.**

As things are now, I have a partially working setup. The patch is activated, I hear the sounds and see some textures, but others are missing, like Link's face and hands on the first moments of the game and the touch screen menues show old textures too.

Please re-write that guide.
![3](https://user-images.githubusercontent.com/43975882/207670070-1ba06137-c12e-4ccc-8bf0-62935f5abe76.jpg)
![5](https://user-images.githubusercontent.com/43975882/207670092-9234ecd0-06ca-49c7-9256-c5f0eabf1602.jpg)

**Comment by Ckosmick** [comment]
Not seeing what this has to do with Project Restoration. The install instructions on the site make no mention of an HD texture pack download. And it seems up to that point you were doing just fine.

**Comment by Shituation** [comment]
> Not seeing what this has to do with Project Restoration. The install instructions on the site make no mention of an HD texture pack download. And it seems up to that point you were doing just fine.

```
Optional but highly recommended:
download this HD texture pack and extract it in the Custom Texture Location. The textures come from the MM3DHD project and currently cover almost all of the game menus and Link's forms!
```

**Comment by Goodland1** [comment]
This seems like a mess. First, turn off your texture filters and set it to linear. Second off, the one for XBOX Controller Layouts is pretty useless. Just changes X with Y and B with A so that it fits with modern buttons. And third up, that HD Texture Pack does want to replace your manually put in Texture, just say you don’t want it to get replaced. Okay, so now we are at the very beginning. You are in Project Restorations Website, you go to the HD HUD Version. Ditch everything you did in the beginning and re-download Project Restoration from the HD HUD Site. It even explicitly states so. And by the way, then do everything like it’s said below. That is more than clear enough. I’d recommend ignoring the HD Texture Pack linked in the HD HUD Site and rather go to Nerrel’s Zelda 3DHD Discord, there’s a newer version of the project with lots more textures covered.

**Comment by Shituation** [comment]
Its a mess because of the messy instructions. 
By the way, I'm not even using this anymore so I'm closing the issue since you all believe the instructions are perfect.

The instructions give you step by step guide, you finish one step and a statement says something like "oh by the way, if you plan on using this on X way, don't do this instead do that" so whathever has been done has to be undone. 

Instructions for going to your friend's house:

1 Open car door.
2 take a seat.
3 turn on the car. (by the way, if you plan to go to your friend house, don't use the car, use the bicycle.)
4 [...]

Going to your friend's house using bicycle:
1 get to the bike
2 take a seat
3 drive 2 blocks (by the way, you may want to take the recommended subway)
4 [...]

...and so on.

**Comment by Ckosmick** [comment]
You must be looking at a different guide. The line about HD textures you keep quoting isn't on the site. https://restoration.zora.re/

**Comment by Goodland1** [comment]
Yeah. It is not on the main site, but it is there when you click on the 
**Playing on higher resolutions? Check out the HD HUD**
Towards the end of the site
