### ISSUE TITLE
D-Pad Masks not working on Citra

### ISSUE THREAD

**Issue by zmarotrix** [leoetlino/project-restoration#24]
Sorry about all these reports. 
I have Deku Mask and I got halfway through Woodfall before I remembered D-Pad buttons are supposed to equip masks. It does not seem to be working for me. I tried ZR + D-Down like Ocarina and that does not work either.

**Comment by leoetlino** [comment]
Hmm, are you sure you've mapped the D-Pad buttons in Citra? They definitely do work for me...

**Comment by zmarotrix** [comment]
Alright I'll try that. I double and triple checked that they were bound correctly.

**Comment by zmarotrix** [comment]
Alright so I'm not sure what exactly changed but it's working. I'll explain my process of events.

- I enabled console and put the filter you said.
- I checked to be sure my controls are bound correctly. They were.
- In game I could move around in the menu using the D-Pad but it would not work with the masks, and nothing was being displayed in console.
- I changed the bindings of my D-Pad to my keyboard 
- It's working just fine and displays in the console.
- I switch it back to my controller (looking the exact same way it did before)
- I try it in game and it's now working...

what.

**Comment by leoetlino** [comment]
Hmm, it sounds like this might be a controller/emulator issue? Project Restoration uses the exact same input data as the rest of the game, so it's very unlikely to be an issue with the fast transform code.

**Comment by zmarotrix** [comment]
I cannot think of what it would be. The fact that it was working in menus is the part that baffles me. Anyway, I'm glad it's working now. It makes not using the touchscreen at all pretty viable.

**Comment by leoetlino** [comment]
Closing since it's working now
