### ISSUE TITLE
Buttons on 8bitdo Pro 2 Controller Stop Working

### ISSUE THREAD

**Issue by euanmatthews** [leoetlino/project-restoration#242]
**Describe the bug**
When playing the Majora's mask, every few minutes my 8bitdo Pro 2 controller's A button and the Left Joystick's horizontal axis stops working. All other buttons work fine. When I go into the control settings and remap the A button the whole controller works again for a few minutes. I'm playing the European version. This issue doesn't occur on the main Citra Nightly builds.

I have tried creating a brand new controller profile and manually remapping all the buttons but that does not help, the issue still occurs. 

**To Reproduce**
This happened to me after following the set up guide. Except from transferring the better joystick folders as I don't use any of those controllers.

**Comment by leoetlino** [comment]
Project Restoration does not come with a custom Citra build. You must have downloaded an unofficial build of Project Restoration and/or malware.

You should use the main/official Citra nightly builds and an [official build of Project Restoration](https://restoration.zora.re/).
