### ISSUE TITLE
The Top Screen's Textures Dont Work And Are Very Blurry

### ISSUE THREAD

**Issue by Aimstrayt** [leoetlino/project-restoration#247]
So I Was Setting Up The Restoration Mod With The HD Hud Mod. And When I Was Done I Wanted To Start To Play But I Saw That The Textures On The Top Screen Of The 3ds Didnt Work And Were Very Pixelated. But The Bottom Screen Worked Very Well.

**Screenshots**
![Ekran görüntüsü 2023-06-18 160357](https://github.com/leoetlino/project-restoration/assets/136976909/741c2349-4bf9-4c0d-b34e-bad5380b6f47)

**Comment by leoetlino** [comment]
Bump up the resolution in Citra's settings. This is not a Project Restoration problem.

Also Why Are You Writing Like This? It Is Extremely Obnoxious To Read And Has To Take You Longer To Write, Right?
