### ISSUE TITLE
Citra becomes unresponsive on Apple M1 when using Project Restoration

### ISSUE THREAD

**Issue by erikmartinessanches** [leoetlino/project-restoration#248]
**Describe the bug**
Is Apple silicon M1 supported by Project Restoration (PR)?

**To Reproduce**
Installed[ this Release of Citra](https://github.com/DarthMDev/citra-nightly-arm64-mac/releases/tag/vulkan-experimental-12). Then tried all available code.bps and exheader.bin files from PR. When starting the game, it makes a sound so I assume PR is loaded. However, after a few seconds the Citra window becomes unresponsive but the game continues to run. 

~When not using PR, the Citra window runs fine but crashes if performing a save state. It is possible to restart Citra and load the save state and continue.~
This seems to be [a Citra bug](https://github.com/citra-emu/citra/issues/6633) on Citra Canary 2519 but in theory, should PR work with M1?

**Additional context**
MacOS 13.4

**Comment by leoetlino** [comment]
Project Restoration runs entirely within the emulated 3DS and so whether the host system is ARM or not is none of this patch's business (and we couldn't even tell even if we wanted to). This sounds like a Citra bug.
