### ISSUE TITLE
Request: Add a label on the Start screen to let the user know the patch is working

### ISSUE THREAD

**Issue by RMZK** [leoetlino/project-restoration#26]
It does not need to be anything fancy, just a label or icon to let the user know the patch is working.

I followed the instructions for Citra and played the game until a got the song of healing so I could unequip the deku mask using the Dpad just to realize the patch was not applied correctly.

**Comment by leoetlino** [comment]
Would playing a sound effect when you start the game be enough? That's a lot simpler than drawing stuff to the screen or editing textures, and it's already being done in the upcoming 1.4.0 release.

**Comment by RMZK** [comment]
it'll work just fine 😀
