### ISSUE TITLE
Great bay Platform / deku platform fix

### ISSUE THREAD

**Issue by conkerbad4day** [leoetlino/project-restoration#27]
Fix heigth of Scientific platform in great bay coast as originaly you would only access it when you dive jump with zora since you added swimming back it would be very nice i know it would require editing the collision but perphaps as a last thing to do when you completed the easiest part of your project it was about 1 and half feet above the water.

 one last thing in MM3d they moved the deku palace song platform for maybe 1 or 2 feet to help reach the deku palace but that not bothering me at all just pointing that out thanks again for your great work!

**Comment by swiftfult** [comment]
The scientific platform height was only like this in the Japanese version. Maybe it's best to keep it as it is so that players don't get confused when they can't get to the platform the way they remember being able to

**Comment by conkerbad4day** [comment]
Closed issue as it is too much job the deku palace would be good but there is too much work intended here, as for the scientific platform your right only on jap but i loved that way to access it.
