### ISSUE TITLE
Optional Saving via Song of Time

### ISSUE THREAD

**Issue by leoetlino** [leoetlino/project-restoration#3]
This was suggested to me and I have no strong opinion on this, though adding a brand new option to save the game is probably a bit difficult to implement, considering it will likely require text edits, when Citra still doesn't support LayeredFS-style patching functionality.

**Comment by SirMrMister** [comment]
The lack of Rewind & Forget is my biggest grip with MM3D, by a mile, but I do understand that it's probably some levels above in difficulty of implementation than most other issues.

**Comment by MotherAndroid** [comment]
So much of the original game's flavour was lost when this was removed! I understand it might be difficult, but if it's at all possible, this feature would be my biggest request!

**Comment by MotherAndroid** [comment]
Another possible suggestion (if this is implemented) would be to disable talking to the owl statues completely? Not for the default build of course, but if it's possible to create an "original save system" build, that would be incredible.
