### ISSUE TITLE
Centre Camera while in fast-swimming or goron-roll mode

### ISSUE THREAD

**Issue by mck007** [leoetlino/project-restoration#30]
Do you think it would be possible to use L while in those modes?
While in fast swimming mode, it is difficult to adjust the camera. The C-stick is difficult to reach as you have to continously press down A. Pressing L doesn't do anything. Would it be possible to activate the centre camera function of pressing L while in this mode?

This counts for goron roll too, where the problem is somewhat less pronounced. As the roll is a toggle, the c-stick is easier to reach, but while we're at it, we could kill two birds with one stone.

**Comment by leoetlino** [comment]
I wonder if this is a bug in MM3D.

**Comment by mck007** [comment]
Can't verify on MMN64, don't know where my N64 is ;)
