### ISSUE TITLE
Add an option for faster aiming speed

### ISSUE THREAD

**Issue by leoetlino** [leoetlino/project-restoration#31]
The current aiming/camera speed is a bit too low, especially when compared to the N64 version.

Increase it and make the new speed optional by ~~only using it if gyro is disabled~~ providing a separate build. (Thanks to @zmarotrix for the suggestion!)

**Comment by Luigimeansme** [comment]
I'm not so sure this is a good idea. I know there are people like me that both like the slow speed, and hate the gyro controls. Increasing the speed and making slow speed exclusive to gyro enabled controls can make it really frustrating to aim precisely where you want, especially in the archery minigames where timing is critical

**Comment by leoetlino** [comment]
Oh, then I'll provide a separate build if I can't manage to add an actual in-game option.

**Comment by Luigimeansme** [comment]
You, my friend, are awesome. Best mod maker yet!

**Comment by Luigimeansme** [comment]
Maybe you can do what you did for Zora swimming and have the speed toggle be on the D pad. Maybe ZL+Up to increase speed so you don't transform into a Goron, and ZL+Down to decrease speed so you don't transform into a Deku, and then remap the pictobox to ZL+Right or something

**Comment by leoetlino** [comment]
I'm concerned about having too many second level mappings... I'd prefer to make it an option or a separate build and avoid changing the mappings a second time ^^

**Comment by Luigimeansme** [comment]
I get that, but wouldn't it be easier to change the mappings rather than have to modify two different builds going forward with every new update?

**Comment by leoetlino** [comment]
Nah, that can be automated, don't worry :)

**Comment by Luigimeansme** [comment]
Ok now I'm curious. How would you automate the changes into two different builds?

**Comment by leoetlino** [comment]
Just edit the build script to make two builds: one without the speed patch, and one with the patch included

**Comment by zmarotrix** [comment]
That is a non-issue. If you want Gyro, you leave it enabled and enable Gyro in the emulator. If you don't want Gyro but want the faster speed, disable the gyro in-game. If you don't want gyro OR the faster speed, disable Gyro in the emulator and enable it in game.

**Comment by Luigimeansme** [comment]
> That is a non-issue. If you want Gyro, you leave it enabled and enable Gyro in the emulator. If you don't want Gyro but want the faster speed, disable the gyro in-game. If you don't want gyro OR the faster speed, disable Gyro in the emulator and enable it in game.

What if you're playing on real hardware? Not everyone is going to be playing on Citra, and I for one don't even have that option
