### ISSUE TITLE
Citra crashes on startup

### ISSUE THREAD

**Issue by ToppestOfDogs** [leoetlino/project-restoration#32]
I'm using an .CXI version of the game, so I don't know whether or not that can be an issue, but when I follow the instructions for the .3DS version in Citra, the games icon disappears and says "invalid region", and trying to start it just crashes Citra.
![Annotation 2019-07-27 145239](https://user-images.githubusercontent.com/17092742/61998447-38fd4100-b07e-11e9-96b1-58a9cccb88f2.png)
![Annotation 2019-07-27 145317](https://user-images.githubusercontent.com/17092742/61998452-5f22e100-b07e-11e9-9aa9-83e6183a4c1b.png)
![Annotation 2019-07-27 145540](https://user-images.githubusercontent.com/17092742/61998467-9f825f00-b07e-11e9-8e00-19d5d6b91b4a.png)

**Comment by leoetlino** [comment]
Is this a MM3D 1.0 dump, or something else?

**Comment by ToppestOfDogs** [comment]
It should be 1.0. There's no version number so I assume so.

**Comment by leoetlino** [comment]
Could you run `ctrtool <path to your cxi>` and post the output to a site like pastebin.com, please?

ctrtool: https://github.com/profi200/Project_CTR/releases
How to use a CLI: https://zeldamods.org/wiki/Help:CLI

**Comment by ToppestOfDogs** [comment]
https://pastebin.com/z9uaSD79

**Comment by leoetlino** [comment]
Looks like you do have 1.0. What version of Citra are you using?

**Comment by ToppestOfDogs** [comment]
Latest canary build

**Comment by leoetlino** [comment]
Hmm, no idea why it wouldn't work then. Try giving the ROM a shorter, less problematic name such as  mm3d.cxi and renaming all the other files to match (mm3d.cxi.exheader, mm3d.cxi.exefsdir).

**Comment by ToppestOfDogs** [comment]
It's still doing the same thing. I can try getting a .3ds dump later and see if that works.

**Comment by leoetlino** [comment]
Enable logging in Citra, set the log level to Debug and check if there are any errors or weird things going on?

**Comment by ToppestOfDogs** [comment]
https://pastebin.com/ABSgJqCq

**Comment by leoetlino** [comment]
Thanks for the log. Looks like it's crashing very early in the boot process, even before it's trying to patch the code... 

     [   4.326968] Debug <Critical> core/hle/kernel/memory.cpp:operator():45: Assertion Failed! New 3DS memory configuration aren't supported yet!

I don't see this message on my end, and I have no idea why you're getting this :/

**Comment by ToppestOfDogs** [comment]
I dunno what's going on then. I tried a .3ds rip and the same things happening

**Comment by leoetlino** [comment]
I'd recommend asking for help on the Citra IRC/Discord, as I can't see why that assert would fail... Let me know if you find out why it doesn't work, even if it's not a Project Restoration issue!

**Comment by ToppestOfDogs** [comment]
Someone suggested that maybe it's allocating too much memory?
https://github.com/citra-emu/citra/blob/master/src/core/hle/kernel/memory.cpp#L25#L70

**Comment by leoetlino** [comment]
That doesn't explain why this assert is failing though:

https://github.com/citra-emu/citra/blob/aca55d0378f1fadb73f1ad54826f19e029a0674f/src/core/hle/kernel/memory.cpp#L45

This project doesn't touch the memory type at all.

**Comment by ToppestOfDogs** [comment]
Well, I've tried a fresh install of Citra and a fresh dump of the game and it's still the same, so I don't know what's happening

**Comment by leoetlino** [comment]
Me neither... if you remove the exheader file and the code.ips file, does the game actually work?

**Comment by ToppestOfDogs** [comment]
Yeah both roms work fine without the mod

**Comment by leoetlino** [comment]
That's very odd. You're using exheader.bin and not the legacy exheader, right?

**Comment by ToppestOfDogs** [comment]
Yes

**Comment by leoetlino** [comment]
Let's talk on IRC/Discord (leoetlino on freenode / leoetlino#1857) to avoid spamming the issue tracker

**Comment by ToppestOfDogs** [comment]
Okay

**Comment by leoetlino** [comment]
Looks like this is because of:

* the NCCH being marked as encrypted when it's decrypted (bad dump)
* the override exheaders having a different title ID from your game
* Citra's title ID heuristic not working in this edge case

I've submitted a PR to Citra to fix this. https://github.com/citra-emu/citra/pull/4862

**Comment by ToppestOfDogs** [comment]
It looks like Citra has broken the mod. Neither the USA or EUR roms work as of canary-1438.
"Error while loading ROM! An unknown error has occurred. Please see the log for more details."
[citra_log.txt](https://github.com/leoetlino/project-restoration/files/3523066/citra_log.txt)

**Comment by leoetlino** [comment]
Thanks for the report. That should be fixed by PR 4900
