### ISSUE TITLE
Play Heart Container Jingle for 4th Piece of Heart

### ISSUE THREAD

**Issue by PRGilland** [leoetlino/project-restoration#34]
This isn't really much of an improvement or quality of life, but I wonder if it would be possible to play the tune for getting a heart container upon getting the 4th piece of heart. This was the case for most other games in the series, including Ocarina of Time, but for some reason never in Majora's Mask, which was always jarring.

**Comment by leoetlino** [comment]
Should be fairly easy.

**Comment by leoetlino** [comment]
Looks like Nintendo/Grezzo kept the "heart get" sound in MM3D and even converted it to a streamed (non-sequenced) sound.

036NA_BGM_HEART_GET

All that needs to be done now is find out where the heart piece code is and make it play a different sound. One thing that might make this tricky is that the sound effect is now streamed and stored in a separate sound archive. Shouldn't be too difficult, though.

**Comment by Clownacy** [comment]
> This was the case for most other games in the series, including Ocarina of Time, but for some reason never in Majora's Mask

Actually, it was apparently [in the original Japanese version](https://tcrf.net/The_Legend_of_Zelda:_Majora%27s_Mask/Program_Revision_Differences#Audio):

"In Ocarina of Time, when you collect a fourth Piece of Heart, extending your life meter, a unique sound effect is triggered. In the Japanese versions of Majora's Mask, this is also true. However, in the American version, collecting the fourth Piece of Heart triggers the same sound effect as collecting the first three."

**Comment by leoetlino** [comment]
Indeed. It looks like it might be a bug that went unnoticed and made its way into MM3D rather than a deliberate change. (the below commit has more details)
