### ISSUE TITLE
Move the Song of Soaring back to its original place

### ISSUE THREAD

**Issue by FloorIceCream** [leoetlino/project-restoration#38]
I think it's more fitting to get it where it was in the 64 version than it just being given to you near the start in the 3DS version.

**Comment by leoetlino** [comment]
IMO, that just makes things more inconvenient for people who want to learn the Song of Soaring as early as possible and use it without having to do the Woodfall main quest, and reverting doesn't bring any benefits... Sorry, I don't think this change should be reverted.
