### ISSUE TITLE
Remove Twinmold Giant Mask Requirement

### ISSUE THREAD

**Issue by DeathWrench** [leoetlino/project-restoration#39]
In the N64 Majora's Mask, you could kill Twinmold in numerous ways without using the Giant's mask. 
In MM3d you can't. Which makes things like using the Fierce Deity mask against Twinmold impossible

Does blue twinmold have weakness to fire like in the original?

**Comment by leoetlino** [comment]
Rejecting, because this would require too many changes and IMO the new Twinmold battle is more interesting. The old one only consisted in slashing Red Twinmold and Blue Twinmold several times, and FD Link already wasn't a good choice in the original anyway.
