### ISSUE TITLE
Make Form Swapping in cutscenes impossible

### ISSUE THREAD

**Issue by Luigimeansme** [leoetlino/project-restoration#40]
Due to how the transformation masks are mapped to the D pad, you can now swap to them in certain mini cutscenes, like when the "Perfect" screen shows up at the end of a minigame, and this can lead to some weird effects. I was doing the archery challenge for Honey and Darling, (already had beaten the first two games in the same cycle) and decided to mess around and switch to the Deku before they gave me my prize. When they did, however, I did not receive the piece of heart as I should. I was instead given another fishing pass, and had to replay the minigame again in order to get the heart piece. Just thought this was worth sharing

**Comment by leoetlino** [comment]
Hmm, I thought I had fixed that with 7142ce2ced381fe7809e423a5b4752de2ab1dd48 (issue #1)... I guess the game must be relying on another method to disable items during that minigame
