### ISSUE TITLE
Compatibility issue with EUR v1.1

### ISSUE THREAD

**Issue by Hedgewolf13** [leoetlino/project-restoration#43]
When attempting to boot EUR v1.1 with code.bps and exheader_legacy.bin (renamed to exheader.bin) in SD:/luma/*tid*/ folder, the game hung on the "Nintendo 3DS" boot screen without progressing. I used the custom Luma **v10.0.1-bps.5**, and the contents from the **v110** folder. 

Deleting the Majora's Mask update via System Settings and using the .ips/.bin for v1.0 did work for me, however. 

Did not test with USA, so this could be an issue with the patch itself (mismatch?), or the BPS patch-_er._ Files used were from the latest release as of writing, "v1.4.2." (v1.4.2-0-g5417db6)

**Comment by leoetlino** [comment]
You should try v100 if you have the 1.1 update installed or pre-installed. From the readme:

>If you have MM3D 1.1, you need to try all three patches and choose whichever works. If your game card came with MM3D 1.1 preinstalled, use v110. Otherwise, try v100 even if you have the 1.1 update installed. If it still won't work, try v101.

In most cases v100 should work if you had the 1.1 update (and *not* a MM3D 1.1 cartridge). After you uninstall the update, *only* v100 should work, unless you have a 1.1 cartridge, in which case you'd need to use v110. Unfortunately I can't make the patcher auto-load the right patch for technical reasons :/
