### ISSUE TITLE
navigate shop inventories with D-Pad

### ISSUE THREAD

**Issue by nr1995** [leoetlino/project-restoration#45]
Simple as it sounds:
You can't navigate shop inventories with the D-Pad in **_Majora's Mask_** **3D**.
Because they're laid out like a block grid,
I find my brain automatically leaves the analog stick for the D-Pad,
but of course it does absolutely nothing.
I can't think of any reason why this wouldn't be allowed in the game.

**Comment by leoetlino** [comment]
After giving this some more thoughts, I don't think this is necessary. The message texts and the UI explicitly tell you to use the analog stick.
