### ISSUE TITLE
immediate “Put Away” sword

### ISSUE THREAD

**Issue by nr1995** [leoetlino/project-restoration#46]
I guess this one won't be very popular
as it's the way **_Ocarina of Time_** and **_Majora's Mask_** and both their 3D variants have always been,
but there's always been something that bothers me
about the way you must stop for a full second,
doing exactly nothing, before you're able to complete an action,
as simple as just putting away your sword.
I just can't think of a reason for it,
and the way it's handled in **_Twilight Princess_** just feels so good and so responsive by comparison.
I don't know, feel free to rip this one to shreds.

**Comment by leoetlino** [comment]
This is out of scope so I'll close this issue, but I'm open to merging a patch if someone decides to work on this (as it shouldn't require too much work to maintain).
