### ISSUE TITLE
one-step open Masks screen

### ISSUE THREAD

**Issue by nr1995** [leoetlino/project-restoration#47]
The Masks screen is now the only screen in the game
that isn't accessible by one button, or two simultaneous buttons.
In a game about masks, I think we could do better.
From what I understand, both [ZR]+[start] and [ZR]+[select]
(Those buttons are probably not called that)
take you to the Map screen.
My idea is simply, why not change one of them to the Masks screen?
If [start] is now Items, [ZR]+[start] seems natural for Masks.
But as long as it's accessible through any combination of buttons at all,
it can be rebound to whatever we like through third-party software.
It's fine as it is now, but it could be better.
Just another thing to make the game quicker and easier.

**Comment by leoetlino** [comment]
I think requiring players to press L or R after opening the inventory screen isn't too unreasonable. It's still very quick and convenient.
