### ISSUE TITLE
Ocarina jump to Songs screen

### ISSUE THREAD

**Issue by nr1995** [leoetlino/project-restoration#48]
I think that when you take out your Ocarina/instrument,
it should take you to the Songs screen by default,
with the option of hiding the songs if you want,
instead of vice-versa.
The default Ocarina screen is just a less functional Songs screen.
The only time I have to take my hands off the controller now, to reach for my mouse,
is to get to the Songs screen when I forget something.
Yes, I can usually remember the most common songs by heart.
No, I can't remember them all, all the time.
Worth noting here is that switching from the Ocarina screen to the Songs screen,
does _not_ interrupt your song, or negate the notes you've played so far.
This means a simple press, wait, press, method would work fine.

**Comment by leoetlino** [comment]
I strongly disagree with changing the default -- there are probably people who like to use the touchscreen and some would rightfully think showing the songs is distracting and makes the default UI more cluttered.

Not opposed to making select/start open the song submenu, though.
