### ISSUE TITLE
Enhance 3D effect to be on par with Ocarina of Time 3D

### ISSUE THREAD

**Issue by Dartz150** [leoetlino/project-restoration#49]
**Description**
Ocarina of time has a better depth 3D effect, giving it a "volume/diorama" feel in a lot of circumstances.

**Additional context**
I'm pretty sure that both OoT3D and MM3D use the same engine, but for some reason Grezzo decided to lower the 3D depth effect with the later, which is weird considering that the effect can be lowered down with the slider itself. To have an example, in MM3D, sometimes the effect can be achieved (kinda) when charging an spin attack or moving the camera with the C nub.

I'll attach 3D captures from both games in similar angles later if needed,

**Comment by leoetlino** [comment]
Sorry, but this is out of scope.
