### ISSUE TITLE
[Feature request] Ocarina playing with D-Pad / C-Stick

### ISSUE THREAD

**Issue by BenjiK4** [leoetlino/project-restoration#52]
Would be nice if the Ocarina was playable like in the N64 version, with the iconic directional layout.
A + ^ v < > ... this could be set to the D-Pad and/or C-Stick.
If possible, it would be great if the on-screen buttons/prompts were changed to directional arrows.

---
I never liked that Nintendo changed the Ocarina buttons so randomly... idk if someone actually prefers the new layout, if thats the case, maybe a toggle to turn this feature on/off

**Comment by leoetlino** [comment]
The D-Pad and C-Stick can't be used as they are already in use (respectively for semi-tones and enhanced free camera control)... Considering I also cannot change the UI, I'm not sure if this is a good idea

**Comment by leoetlino** [comment]
After giving this some more thought, I don't think this can be done properly. The A button is also used by the new button scheme, and it doesn't have the same effect as the N64's A button, so both layouts can't coexist, unfortunately.
