### ISSUE TITLE
[QoL improv] Bricks in front of Stone Tower Temple

### ISSUE THREAD

**Issue by mck007** [leoetlino/project-restoration#56]
I thought about a potential QoL improvement concerning the moving bricks directly in front of the Stone Tower Temple (STT) entrance.
Would it be doable to keep them in place after a first alignment? That would considerably reduce the need to play elegy. If it weren't for the tediousness of the whole process, I would not propose this. I think that all in all, this is were most casual players will play this song the most by far, having to backtrack between normal STT and upside down STT if they are stuck. A big source of frustration, as I can tell from experience. Perhaps it is already alleviated somewhat by the shortening of the song process.

**Comment by leoetlino** [comment]
Too tricky IMO. Flags for the 3DS are extremely poorly documented and modifying them brings the risk of corrupting save data. I think the song being shorter is good enough; you only need to play the Elegy to enter STT (non-inverted), and that's very fast nowadays.
