### ISSUE TITLE
[Feature request] A/B button prompt removal?

### ISSUE THREAD

**Issue by MotherAndroid** [leoetlino/project-restoration#57]
**Description**
Removing the prompts for buttons on the top screen (i.e, Open, or Roll).

**Additional context**
The remakes did an awesome job de-cluttering the top screens for OoT and MM, and it goes a long way to improving the overall experience, visually.
The buttons which give the player information on when objects can be interacted with however are so big (especially on a 3DS screen) and usually pointless (yeah, I know I can open the door)!
Removing these would leave just the timer on the bottom screen (which is vital to the game) and would centre the UI, making the game look much cleaner as a result.
![A Button](https://user-images.githubusercontent.com/53223256/63542266-ea758200-c517-11e9-9365-8478c96e13a6.png)

**Comment by ToppestOfDogs** [comment]
You could also dump the UI textures and erase the words and ui elements, then load the custom textures. I've done something similar in OoT3D before.
![cit2](https://user-images.githubusercontent.com/17092742/63551808-1981f880-c504-11e9-9c84-71f882b84ba9.png)
Here I've replaced them instead, but you could easily just erase them.

**Comment by DeathWrench** [comment]
I don't know why you did this to leo man, I literally made like 5 different versions of what you're asking for. Yet you STILL bug leo, and you don't even ask him to do what  you REALLY wanted which was to edit the digital clock to be just the current hour. Unbelieveable dude.
I'm gonna post this AGAIN just in case you want to actually try it out.

https://cdn.discordapp.com/attachments/515842332201975821/614331965989978122/minimalisthud_3.zip

**Comment by leoetlino** [comment]
Sorry, this is out of scope.

**Comment by MotherAndroid** [comment]
Absolutely, just wasn't sure how much work it'd take. Thanks for the reply regardless!
