### ISSUE TITLE
JPN version compatibility

### ISSUE THREAD

**Issue by Stormsinger-Frostclaw** [leoetlino/project-restoration#61]
**Description**
I would like to know if this project could be made compatible with the JPN version of MM3D.

**Comment by Vixenko** [comment]
It is compatible with the JPN version. Using unpatched MM3D v1.0 JPN with the v100 mod.

**Comment by Stormsinger-Frostclaw** [comment]
Ah, I guess I will need to find a copy of MM3D v1.0, since the version I have is 1.1. Thanks. :)
