### ISSUE TITLE
[Zl+Zr] Changing arrows

### ISSUE THREAD

**Issue by conkerbad4day** [leoetlino/project-restoration#62]
I know you added a way to change arrow when aiming but it would be more fitting to have it mapped to Zr in order fire, ice, light and Zl light, ice, and fire it would be very simple to change and fit very well with all the stuff you already mapped thanks.

**Comment by leoetlino** [comment]
ZR is used as a modifier, so I don't want to map things to ZR alone for consistency reasons. Furthermore I don't really see the point of having another toggle button.

**Comment by conkerbad4day** [comment]
It is when aiming friend i want it to change arrows direction not map anyting anyway it is not even used when aiming so why not?

**Comment by conkerbad4day** [comment]
I mean you already mapped Zl to change arrows but it is ankward for me as in others zelda both trigger change arrows and i prefer Right can you at least tell me how to change it?
