### ISSUE TITLE
Is it possible to change Tatl's text?

### ISSUE THREAD

**Issue by FoetusSheldon** [leoetlino/project-restoration#65]
Tried out the new Odolwa fight and noticed that Tatl still mentions an "eye" in one of her prompts. I just thought that it may make sense to change these if the eyes have been removed, but of course I don't know how much of a pain it would be to implement.

**Comment by SuperSmashBrony** [comment]
This is also an issue with the Bombers Notebook, which still says to open with START when you hover over it in the menu, even though it’s been changed to SELECT.

**Comment by GeneraLight** [comment]
Please fix for consistency's sake.
