### ISSUE TITLE
[Bug report] Game refuses to start; Citra stops on black screen

### ISSUE THREAD

**Issue by mrfreela** [leoetlino/project-restoration#74]
while everything is seemingly in place, when i try to load up MM3D via Citra, it just doesn't load.  it hangs on a black screen not doing anything, and Citra properly crashes if i try to restart or stop the emulation.

*mention of other versions of project restoration removed; irrelevant since this is on Citra, only v100 is possible*

this is, of course, with version 1.0.0 of majora's mask 3d.

name of the game file: majorasmask3d1.0.3ds
exheader file: majorasmask3d1.0.3ds.exheader (is read as an EXHEADER File, not BIN, and the file is in same folder as game file)
exefsdir folder: majorasmask3d1.0.3ds.exefsdir (has code.ips inside, and the folder is in same folder as game file)

this issue exists exactly the same on both the most recent Citra builds, as of 9/13/2019

**Comment by DeathWrench** [comment]
1.00 only works with citra, .bps is not supported which is why only 1.00 works. 1.00 is an .ips patch

You can find this information on the main page here: https://github.com/leoetlino/project-restoration

**Comment by mrfreela** [comment]
this is reasonable enough; about what i expected.  i have the 1.00 game patch, and am trying to use the 1.0 bps patch, however it still leads to the black screen and refusal to start i otherwise described.

**Comment by mrfreela** [comment]
solution found!  turns out something was important that i didn't think was so, or at least did not realize.  if someone manages to have the same problem as me, i'm gonna list all the things i wasn't certain of here just so there's a specified resource, or at least another one if i just couldn't find ones that already existed in the detail i was looking for:

1. make sure your majora's mask rom, the exheader file, and the exefsdir folder are in their own folder; don't just lump them up together in one big rom folder.

2. make sure your exheader file is *literally* an EXHEADER File type; make sure you can see File name extensions, and when you change the file's name make sure it *does* ultimately become an EXHEADER File, and is not still a BIN file.

i believe that's all i was uncertain about, the "make sure the rom, exheader and exefsdir folder have their own folder" detail being the most important one that i didn't realize.  now the deku form actually has proper acceleration and it is good.  godspeed y'all o7
