### ISSUE TITLE
[Feature request] Retain Arrow Switches

### ISSUE THREAD

**Issue by shadowpendant69** [leoetlino/project-restoration#76]
The new arrow switching ability you released as part of this patch works pretty well, and Id gladly use it over having to consistently open the menu to swap arrow types manually. Only there is a bit of a repetitive issue

What I am referring to is how the arrow type switches back to the default arrows selected after you end your first person aim, it can be quite the pain, having to switch back to the same arrow type each time you take out your bow, so if its possible could you make it so that when you swap from one arrow type to the other, you can retain that arrow type until you switch it to a different one yourself?

**Comment by leoetlino** [comment]
Sure, why not. I think making the switch permanent would only require changing the equipped arrow item
