### ISSUE TITLE
[Feature request] Restoration of the original majora's mask n64 soundtrack

### ISSUE THREAD

**Issue by MeinFuhrerBradley** [leoetlino/project-restoration#77]
Majora's mask 3d soundtrack have a  of terrible amount reverb effect in comparation of the original ost and the songs simple sound terrible.

I would like to know if it is possible to inject or restore the original soundtrack.

**Comment by TheLegendOfLame** [comment]
> I would like to know if it is possible to inject or restore the original soundtrack.

Believe it or not, it's already been done by DeathWrench
https://github.com/DeathWrench/Majora-s-Mask-N64-OST-to-3DS/releases/

**Comment by MeinFuhrerBradley** [comment]
I would like to know if it is possible to apply the songs in citra too

**Comment by MeinFuhrerBradley** [comment]
Thx, i shall talk with deathwrench to see if it is possible to apply the songs on citra too.

**Comment by GeneraLight** [comment]
How do I install this?
