### ISSUE TITLE
[Feature request] Faster transition in songs after being played once

### ISSUE THREAD

**Issue by MeinFuhrerBradley** [leoetlino/project-restoration#78]
You've already apply this same feature on the song of soaring,

I would like to know if it is possible to apply this same feature on all the other songs.

**Comment by GeneraLight** [comment]
Song of Double Time and Elegy of Emptiness are perfect candidates.

**Comment by Stormsinger-Frostclaw** [comment]
If I recall, the Elegy of Emptiness already does this as well.

**Comment by leoetlino** [comment]
It's kind of tricky to implement for all the other songs and the ones that need it most (SoS and EoE) already have it done. Moreoever the other songs aren't just the ocarina song repeated (like SoS and EoE) and I don't think they are played often enough to warrant removing the repetition.
