### ISSUE TITLE
Just a black screen

### ISSUE THREAD

**Issue by MeowzerBowzer** [leoetlino/project-restoration#79]
I just get a black screen on citra. I tried every patch version
and both citra versions.

I have zelda_mm.3ds in the root folder for my games and in it then:
zelda_mm.3ds.exefsdir 
and in it:
code.ips 
zelda_mm.3ds.exheader

Its the initial majoras mask release.

**Comment by leoetlino** [comment]
The exheader is in the wrong folder. It should be next to zelda_mm.3ds, *not* in the exefsdir
