### ISSUE TITLE
Fix Odolwa

### ISSUE THREAD

**Issue by leoetlino** [leoetlino/project-restoration#8]
Odolwa is way too... passive in the remaster. He doesn't do anything most of the time, and it's difficult to get him to use some of his attacks. What's worse is that there is essentially only a single way to defeat him now: stun him with a Deku Nut, then hit the eye weakpoint, rinse and repeat.

From Nerrel:

> (...) [T]his is what I found when trying to fight Odolwa in Link's form only.   If you view on YT, you can use the timestamps in the description:  https://youtu.be/I_oJUrE4dAE
> 
> 1. Right from the start, the main thing that bothers me is that you can't do damage when landing attacks.  I'd like those swings to actually inflict damage.
> 2.  At 0:10 he does a charge attack, after which he's vulnerable to attacks, but only a swing or two.  Then the eye comes out and you have to strike it.  I'd like to be able to just hit him anywhere without the eye requirement.  The eyeball can still pop out, just change it so that it's not the exclusive weak point.
> 3.  At 0:28 he starts charging around and becomes vulnerable to arrow strikes.  I don't recognize this move from the original game, but it's one of the few windows he gives to arrows in the remake.
> 4.   At 0:36 he seems to dodge all arrow attacks while dancing.  I do hit him at the end of this animation, but it seems like he was transitioning to another attack.  I'd like him to be more vulnerable during dances.
> 5.  At 0:52 I try slicing him during the "run in circles animation" but it doesn't work.  I'm not sure if he's vulnerable to sword attacks while running, but he definitely should be.
> 6.  At around 1:00 he dodges arrow attacks, but can apparently be stabbed from behind.
> 7.  In the original fight he's much easier to shoot.  There are more windows to hit him during his dances and he doesn't block 100% of the time.   He's especially vulnerable when doing his windmill dance
> 8.  At 1:44 he does a spin attack, which I'm not sure I've ever seen in the remake.  Is this one of the attacks that's still in the game but unused?
> 

---

* Make Odolwa use his attacks more aggressively.
  * [x] Make the fire ring attack happen more often. Apparently it can only happen when Odolwa's HP is low.
  * [x] Spin attack
  * [x] Shorten the pre-Dash animation
* [x] Revert the change to Odolwa's starting life/HP (15) and set it back to 20 to compensate for the additional methods of attacking him.
* More reasonable blocking
  * [x] Allow dealing damage to Odolwa whenever an attack is not blocked by his shield
* [x] Get rid of the eye weakpoint mechanic (but keep the eye).
  * [x] Make the stun state last longer. In this state attacks aren't blocked by the shield.
  * [x] Deku Nuts will no longer trigger an instant "eye out" state but will just stun Odolwa.
  * [x] Update life and cycle damage counter in stun state (rather than in "eye out" state)

**Comment by NReun** [comment]
Perhaps let him get stunned by deku nuts standing up, so you make use of arrows or bubbles to damage him. With the sword it's way too easy, so if one of his animations could be repurposed to look like he's stunned that would be nice.
Don't let him use his shield while preparing the charging animation, making it a high risk, high reward situation where you can strike or get damaged.

**Comment by DeathWrench** [comment]
Would there be a way to add the fire back in?
