### ISSUE TITLE
Crash during Gyorg phase 2 fight (collision-related memory corruption)

### ISSUE THREAD

**Issue by TomGoat98** [leoetlino/project-restoration#80]
The game hard-crashed when fighting Gyorg in the second phase of the fight.

Whilst I'm unsure of how the crash occurred, the fight took place in the second, underwater phase of the fight, on the night of the first day, with the Song of Double Time slowing down time. It also occurred when I knocked out Gyorg with the mines the second time, and hitting him as Zora Link.

I have attached the crash dumps that Luma had generated

[MM3d_PR_Gyorg_Fight_Bugs.zip](https://github.com/leoetlino/project-restoration/files/3676288/MM3d_PR_Gyorg_Fight_Bugs.zip)

**Comment by leoetlino** [comment]
looks like it's crashing in Gyorg's collision handling function...

```
Processor: ARM11 (core 0)
Exception type: data abort
Fault status: Translation - Section
Current process: Joker (0004000000125600)

Register dump:

r0             00000001            r1             00000005            
r2             0000e818            r3             0809f360            
r4             0809e5f0            r5             002802c8            
r6             00000000            r7             00013820            
r8             00000016            r9             00000001            
r10            00000002            r11            00000001            
r12            00000081            sp             0ffff390            
lr             007cfb90            pc             002a06c0            

cpsr           68000010            dfsr           00000005            
ifsr           00000004            far            0000e818            
fpexc          40000700            fpinst         ee200a20            
fpinst2        ee200a20            
FAR            0000e818            Access type: Read

Code dump:

  2a0694:	0a000010 	beq	0x2a06dc
  2a0698:	e59421f8 	ldr	r2, [r4, #504]	; 0x1f8
  2a069c:	e1520005 	cmp	r2, r5
  2a06a0:	159f33dc 	ldrne	r3, [pc, #988]	; 0x2a0a84
  2a06a4:	11520003 	cmpne	r2, r3
  2a06a8:	159f33d8 	ldrne	r3, [pc, #984]	; 0x2a0a88
  2a06ac:	11520003 	cmpne	r2, r3
  2a06b0:	1a000005 	bne	0x2a06cc
  2a06b4:	e5943d6c 	ldr	r3, [r4, #3436]	; 0xd6c
  2a06b8:	e08e2201 	add	r2, lr, r1, lsl #4
  2a06bc:	e7932002 	ldr	r2, [r3, r2]
  2a06c0:	e5922000 	ldr	r2, [r2]
```

For some reason, this->collision.col[k]._.colliding_info is a nullptr...

**Comment by leoetlino** [comment]
Do you have any way to consistently reproduce this issue? I haven't been able to get it to crash

**Comment by TomGoat98** [comment]
I've only had it crash the twice, only under Slowed time and on night of the first day. I'm yet to figure out a consistent methodology.

**Comment by leoetlino** [comment]
Actually, this is even worse. collision.col[1].colliding_info is not just a null pointer, it's a bad pointer whose value is completely garbage (0000e818)...

**Comment by leoetlino** [comment]
And the pointer value is different in your two crash dumps. Smells like memory corruption, but that's impossible to debug even with the dumps :/

**Comment by frutch** [comment]
it feels like it occurres after spaming the b button multiple times. had the hard-crash to times in the row after i tried to kill him with B. so I decided to swim near by him touse R for dealing damage.

**Comment by leoetlino** [comment]
@frutch Thanks for the lead. Are you able to reproduce the crash consistently by attacking with B (to use the Zora boomerangs, I suppose?)

**Comment by frutch** [comment]
I guess you have to be eaten before you attack him. I did a video for you. [Check it out](https://youtu.be/zSsEpZLlhzY)

**Comment by leoetlino** [comment]
Thank you very much for the video! I'll investigate it and let you know if I figure out what is going on...

For now, I recommend using Zora Link's barrier attack.

**Comment by leoetlino** [comment]
Unfortunately, it looks like this is still very inconsistent. I tried to reproduce the crash 7 times, and I only saw memory corruption once:

```
[ 196.056211] Debug.Emulated <Debug> core/hle/kernel/svc.cpp:OutputDebugString:816: HandleFastTransform: transforming (Zora)
[ 202.657530] HW.Memory <Error> core/memory.cpp:Read:181: unmapped Read32 @ 0x09CD4500 PC @ 0x002A06D4 LR @ 0x007D0630
[ 202.657539] HW.Memory <Error> core/memory.cpp:Read:181: unmapped Read32 @ 0x00000000 PC @ 0x002A06D4 LR @ 0x007D0630
[ 222.424976] Debug.Emulated <Debug> core/hle/kernel/svc.cpp:OutputDebugString:816: FixFreeCameraReset: resetting camera mode (Zora swimming)
[ 238.727070] HW.Memory <Error> core/memory.cpp:Read:181: unmapped Read32 @ 0x09CD4500 PC @ 0x002A06D4 LR @ 0x007D0630
[ 238.727076] HW.Memory <Error> core/memory.cpp:Read:181: unmapped Read32 @ 0x00000000 PC @ 0x002A06D4 LR @ 0x007D0630
```

On console the game would have crashed at t=202.657530, but Citra lets the game continue to run so there are further errors that are caused by the same corruption issue.

Memory corruption bugs really aren't my favourite. D:
