### ISSUE TITLE
Razor Sword improvement

### ISSUE THREAD

**Issue by DorsalAxe** [leoetlino/project-restoration#82]
I don't know if this is considered to be within the scope of this project, but the Razor Sword is something that's always been the subject of criticism, even in the original game. I feel like it's ripe for improvement and any change would be welcomed by the community. I'm surprised that it wasn't altered for MM3D given all the other changes to the game, and I'm sad it still sucks because its design is really cool and unique.

Basically it's utterly impractical as a weapon. You can use it up to 100 times before it breaks, which on its own isn't an issue, but for some reason you inexplicably lose it whenever you go back in time (with no warning, and despite keeping _every_ other sword in the game). This means it's only useful for a maximum of 2 days, but only as long as you use it sparingly. A lot of players tend to first obtain it quite late into the cycle and sort of forget about it after realising they can't keep it. As a result, the sword ends up serving as merely a brief quest item to turn the L1 Kokiri Sword into the L3 Gilded Sword.

I've seen lots of suggestions over the years about how to improve it, but I think the simplest solution that wouldn't particularly ruin anything is to allow Link to retain the sword after travelling back in time. The 100-use counter still acts as a limit on its use and still encourages the player to improve the sword further, but keeping it across cycles actually makes it viable as an upgrade and allows players to more comfortably delay doing the Goron race if they so choose.

**Comment by GeneraLight** [comment]
Yeah, I completely agree. The Razor Sword's presence and impact are almost non-existent in Majora's Mask. It needs to be a permanent upgrade so it can be more useful and fleshes out the variety of the game.

**Comment by mck007** [comment]
I would even go further and take away the 100 cuts limitation.
For a casual gamer who doesn't know the importance of the sword as an intermediary, it would certainly be an improvement, as he can postpone the second upgrade to the next cycle (or any subsequent cycle for that matter) without any worrying.
The experienced player wouldn't use it anyhow in it's vanilla state and not fall into the trap of paying the 100 rupees.

**Comment by leoetlino** [comment]
I'm sorry, but I don't want to deviate too much from the original game, especially as it would require changing text in all languages.

**Comment by GeneraLight** [comment]
:/

The original game was flawed too

**Comment by Willburd** [comment]
Despite this being a closed PR, I felt i should give my thoughts. I don't actually think there is any dialog specific to the reversion to kokori sword when using song of time, at least from memory. It may be in the item description, but at least from the original N64 dialog there seems to be no reference. 

Other things to note, I worked on a patch for n64. Some of these details may carry over to 3D, but I don't know how many. The razor sword there had a counter that was set to 100, and would count down to 0 with each sword impact. On 0 it would stop decrementing, and break the sword. The counter would only decrement when the sword was the razor sword. The counter was retained with both owl statues and song of time, (if you went back in time with 10 swings, it would have 10 swings left when you load the file, even on day 1!) The only thing that I don't believe I was able to figure out was that if you had the sword stolen, and went back in time, it would reset to kokori. 

Other than that, all I can say is that it's really an improvement for a weapon most people will just skip anyway, so I don't see any harm to gameplay. Other then a sword that does 1 damage less than the max level "practically free" upgrade that you can get within 10 minutes of getting the razor sword if you already have snowhead beaten.
