### ISSUE TITLE
[Feature request] Fierce Deity's Mask

### ISSUE THREAD

**Issue by ymmij12** [leoetlino/project-restoration#85]
Can you do so that you can use the mask everywhere? Once you have received this mask you have managed everything.  Don't understand why you can't use it everywhere.  If you do not think so, I would appreciate if you can use the last day or the last 5 minutes.  Was probably the biggest disappointment when I got the mask first time on the N64.  You struggling to have The mask in the inventory because you think is special(it have a dot in The inventory), but when you get it you can only use it on the boss.

**Comment by leoetlino** [comment]
This is out of the scope of the project.
