### ISSUE TITLE
[Feature request] Deku's original bubble shooting trajectory + fast action to switch between original and new trajectory.

### ISSUE THREAD

**Issue by MeinFuhrerBradley** [leoetlino/project-restoration#87]
it is well known that the trajectory of the original deku bubble was much less straight than the new straight line and less difficult to reach the target majora's mask 3d trajectory, this new trajectory eliminates the difficulty of shooting at targets in the game, it would be good if you could restore the original trajectory, and I don't know, maybe change between the trajectory of the shots with a quick action, as you do with the swimming of the zora.

Thanks for everything.

**Comment by GeneraLight** [comment]
Would be nice

**Comment by leoetlino** [comment]
I'm closing this issue because it's honestly unlikely I'll work on it, and I don't think it's fair to give you the impression that it's going to be done at some point. It is way too minor and IMO adding a switch between the trajectories would be overkill.
