### ISSUE TITLE
 [Feature request] Faster Mask transition (animation skip?)

### ISSUE THREAD

**Issue by Felina-Lain** [leoetlino/project-restoration#88]
After the first dozens of times putting on the various race mask, the transition with Link screaming becomes annoying.
I was hoping it'd be more like this video
https://youtu.be/G9Bg1bbCgWo?t=6s
Which showed your patch, but when I tried it, while the shortcuts button work, the animation is there.

So if it's at all possible, to remove the animation after it played once? 

And thanks for the wonderful patch!

**Comment by leoetlino** [comment]
That's already been implemented by Nintendo. Just press any item button again during the mini cutscene to skip it.
