### ISSUE TITLE
Add additional transformations to the D-Pad via ZR Button

### ISSUE THREAD

**Issue by Anonymine** [leoetlino/project-restoration#92]
Title mostly sums up my request. Essentially, holding ZR (similar to how the I & II items work) would permit you to access different transformations. It would look something like this:

ZR + Up: Fierce Deity
ZR + Left: Giant

While the aforementioned masks are only used in specific circumstances, I feel as though this would serve to streamline the game even more effectively and prevent excessive inventory management.

**Comment by leoetlino** [comment]
I'm concerned about adding even more second-level mappings as they are not easily discoverable.

**Comment by Anonymine** [comment]
> I'm concerned about adding even more second-level mappings as they are not easily discoverable.

In general, I don't think most people's first instinct would be to use the D-Pad if they were just going into the mod blind - the reason most people even know that option exists is largely due to you actually writing it in the description. Hell, the reason most people know that ZR options exist are also courtesy of you mentioning it, so I don't think it would be that far of a leap. Your call at the end of the day, but just wanted to say that in its' defense.

**Comment by PRGilland** [comment]
Someone did make a companion texture pack for this mod that shows some of the second-level bindings on the touch screen buttons. Not sure about the d-pad though.

**Comment by Luigimeansme** [comment]
> Someone did make a companion texture pack for this mod that shows some of the second-level bindings on the touch screen buttons. Not sure about the d-pad though.

Wait, is this console compatible? Please post a link if so, I would love this!

**Comment by PRGilland** [comment]
> 
> 
> > Someone did make a companion texture pack for this mod that shows some of the second-level bindings on the touch screen buttons. Not sure about the d-pad though.
> 
> Wait, is this console compatible? Please post a link if so, I would love this!

Sorry, it was a texture for Citra, using Citra's texture dumping and loading function.

**Comment by leoetlino** [comment]
>In general, I don't think most people's first instinct would be to use the D-Pad if they were just going into the mod blind - the reason most people even know that option exists is largely due to you actually writing it in the description.

That's true. And I guess text editing in the future will address that issue.

**Comment by leoetlino** [comment]
I ended up only adding a mapping for FD Link; the Giant's Mask is kind of a pain to handle as it is a special case in the game code :/ Hopefully that shouldn't be too much of an issue as the Giant's Mask is so rarely used.

**Comment by tstandley** [comment]
Would it be possible to allow the FD mask anywhere?

**Comment by leoetlino** [comment]
Yes, but actually no. The game really isn't designed to let you use the mask everywhere. Dialog messages are missing so the game will softlock every time you talk to some NPCs. Opening doors crashes the game, etc. "FD anywhere" is also out of the scope of the project, so I am unwilling to add it.
