### ISSUE TITLE
Some slight D-Pad transformation issues

### ISSUE THREAD

**Issue by Anonymine** [leoetlino/project-restoration#93]
D-Pad mask shortcuts do not work while a) atop the clock tower, and b) while in Twinmold's boss room after having beaten them. Reproducing this isn't overly difficult - just go to the rooms in question & try using the shortcuts. Not overly important, but figured it was worth mentioning anyway

**Comment by PhlexPlexico** [comment]
I'm not sure if this is so much a restoration bug? I can't say for certain about twinmold, but I know in the clock tower in the non-modded version, you are not able to transform into any other form. Even if you enter as a different form and remove the mask from the buttons, you won't change back into human Link.

**Comment by leoetlino** [comment]
It looks like this was fixed by your patch (https://github.com/leoetlino/project-restoration/commit/deff9fc48b1da93eb635a039713c69c57c8a5f31). Thanks!
