### ISSUE TITLE
Odolwa's eye not entirely removed

### ISSUE THREAD

**Issue by BarrowRoll** [leoetlino/project-restoration#94]
I've found a way to make the eye on Odolwa's head still appear. When he initiates his spin attack (you can tell before he does this by his manic sword swinging, and the unique sound it makes), burrow into a Deku Flower and float above him while he performs the spin attack. Once he finishes, he'll stand around looking for you and the eye will be open on the back of his head. This is only cosmetic though, as dropping a Deku Nut on it won't put him the stun state from the unpatched version of the game.

I've noticed another issue with Odolwa, though I'm not sure if this was intentionally added to the game by Grezzo or not. When Odolwa performs the spin attack, sometimes he goes right into the stun animation afterwards, almost as if the spinning made him dizzy. This doesn't happen every time though, and I've noticed it happens most often if you stayed burrowed in a Deku Flower while he spins.

I'd also like to take this moment to mention that I think the Odolwa fight still needs some touching up in general. It's great that (for the most part) the eye is removed, and that you can actually damage him by other means again. However, right now after stunning him, you can usually only get 1 sword swipe in, sometimes 2 if you're lucky. This is in contrast to the fight in the N64 version where you can usually get 2, maybe 3 swipes in if you're lucky. Also, he still stands around like a dum dum if you burrow into a Deku flower, or use them to float above his head. The same strategy from the unpatched game of dropping Deku nuts on his head is still probably the most reliable way of stunning him at this point because he has no defense against it.

My suggestions, if possible, would be:

1. Increase the stun the duration after hitting him with an arrow, or any other means that currently works, so you can consistently get 2 sword swipes in. 

2. Remove the braindead standing around when using the Deku Flower against him. Keep the ability to stun him with Deku nuts from above, but make the player actually work for it by having to at least chase a moving target.

3. Odolwa also seems less aggressive in general compared the N64 version. If possible, maybe have him use his attacks more often. Though there's an argument to be made that the boss from the first dungeon maybe shouldn't be too difficult.

**Comment by BarrowRoll** [comment]
Was just able to get the eye to appear the back of his head again by dodging his lunging stab attack with a deku flower and floating above.

**Comment by leoetlino** [comment]
>you can usually only get 1 sword swipe in, sometimes 2 if you're lucky. This is in contrast to the fight in the N64 version where you can usually get 2, maybe 3 swipes in if you're lucky.

Yes, this is on purpose, as not limiting damage completely trivialises the fight.

https://github.com/leoetlino/project-restoration/blob/9e9b94041c41892a692a1736269e054e79b09887/source/rst/fixes/boss.cpp#L197-L202

>Remove the braindead standing around when using the Deku Flower against him. Keep the ability to stun him with Deku nuts from above, but make the player actually work for it by having to at least chase a moving target.

Because of how badly Deku Link maneuvers in the air, I can't remove that state without making it extremely tedious to stun Odolwa with Deku Nuts. The wait duration has already been reduced; if you take too long Odolwa will summon falling rocks.

**Comment by leoetlino** [comment]
The "open eye when Deku Link is floating" logic can probably be removed.

**Comment by leoetlino** [comment]
Apparently it's not that simple... Seems like the eye is tied to the animation, so I can't get rid of it easily. Since this is purely cosmetic and doesn't affect gameplay at all, I think I'll leave this as is.

If you or anyone else has a patch, I'll be happy to include it.
