### ISSUE TITLE
How difficult would it be to implement the original clock?

### ISSUE THREAD

**Issue by wreaver** [leoetlino/project-restoration#95]
I apologize in advance if this is too much, but how difficult would it be to implement the original clock from the N64 version? I personally think it's much better aesthetics-wise and fits the game better compared to the new one. This is mostly curiosity though.

**Comment by leoetlino** [comment]
Very difficult, and the 3DS does not really have enough screen estate for this to be a good idea IMO.

**Comment by wreaver** [comment]
I imagined that was the case but I still wanted to know. Thanks for replying!
