### ISSUE TITLE
Quick Switching Arrows Allows Spam

### ISSUE THREAD

**Issue by PhlexPlexico** [leoetlino/project-restoration#96]
**Describe the bug**
If you're quick switching from default arrows to ice/light/fire arrows, you can spam as many arrows as you please. The sound effect that indicates its supposed to prevent you still plays.

**To Reproduce**
Apply default arrow to button, quick swap to fire/ice/light and spam to your hearts content.

**Screenshots**

**Additional context**
Seems there's a delay on the original that prevents a spam as such, and the quick switch context doesn't take that into account. This can be observed by equipping an elemental to an arrow button and attempting to spam it as well.

**Comment by leoetlino** [comment]
It looks like this was fixed by your patch (https://github.com/leoetlino/project-restoration/commit/deff9fc48b1da93eb635a039713c69c57c8a5f31). Thanks!
