### ISSUE TITLE
(Citra) Pressing ZR makes pressing A do nothing unless you hold ZR +A

### ISSUE THREAD

**Issue by pkcraze** [leoetlino/project-restoration#97]
Any time I press ZR, it makes my A button stop responding for some reason. I can then only get an A press by pressing ZR+A. If I go into my controller configuration, A still says "Button 2" despite it not working. If I re-set it to the same button, it starts working normally again until I press ZR.

Using Latest Citra Nightly build, MM v100, ps4 controller with motion controls through DS4Windows.

**Comment by leoetlino** [comment]
It sounds like your controller configuration is broken. Without the patch, what happens when you press ZR while swimming in Zora form?

**Comment by pkcraze** [comment]
> It sounds like your controller configuration is broken. Without the patch, what happens when you press ZR while swimming in Zora form?

Interesting. When I remove the patch, pressing ZR or ZL (mapped to R2 and L2 respectively) triggers the shield or tagetting but when I let go of the button it stays active. So Im forced to either hold down the buttons or remap the controls. I guess it is a controller issue, never had this happen before.

**Comment by pkcraze** [comment]
Problem solved! It is a ps4 config problem. The R2 and L2 buttons each have 2 separate keypresses on Citra for whatever reason (An input for pressing the button down, and another for releasing it). So when assigning controls with R2, you have to hold the button down, click assign to ZR, then release it for it to work properly.

Sorry it isn't mod related, I've just never had this issue.
