### ISSUE TITLE
[Feature request] Possible Update Patch?

### ISSUE THREAD

**Issue by Luigimeansme** [leoetlino/project-restoration#98]
This may be completely out of scope of the project so feel free to shoot me down, but would it be possible once all the bugs are ironed out to make this into an update for the game that you install as a CIA, rather than having to use a modified version of Luma? I feel like if this was possible, it would be nearly completely idiot proof, and just be a lot more convenient to get working overall

**Comment by Luigimeansme** [comment]
Or maybe even make it a patcher similar to the Scarlet Study english patch for Dai Gyakuten Saiban

**Comment by leoetlino** [comment]
Distributing title updates is a can of worms: it'd require users to install the update permanently and make permanent changes to their console, require them to disable signature checks, and make the release project more complicated for me.
