### ISSUE TITLE
Can you activate the walk, when we are in first person? 

### ISSUE THREAD

**Issue by Nivehk** [leoetlino/project-restoration#99]
**Description**
I was wondering for a time if it is possible. None of them N64 or 3DS had a second analog. But on these day, thats a different story. So I think that allow us to walk when we are in first person will just increase the experience, we got even the gyro for better aim. Can't move of our place is a missadvantage

**Comment by leoetlino** [comment]
Too complex, and the only stick we could use is the C-Stick.
